#!/usr/bin/env python3
"""ph97 — the in-kernel compare, priced against the libc one. TWO questions.

    python3 patterns-php/ph97-optarg-unwritten/controls/libc_compare.py
    python3 .../libc_compare.py --no-cost     # part A only (seconds)

=============================================================================
WHY THIS CONTROL EXISTS
=============================================================================
`c/kernel.c` implements `strcasecmp(3)` itself instead of calling libc's, and
`spec.md`'s divergence ledger says that is **a measurement decision as much as a
fidelity one**. `RECAP_PHP.md` **F119**: `kernel_exclusive_ir` (family A1) is
SYMBOL-SCOPED and structurally excludes callee work, and on `ph53` **all of a
±7 Ir swing lived inside a libc `memset` A1 could not see**. A kernel whose
whole computation sat inside libc would read approximately zero in the column
this programme publishes.

So the substitution owes two things and this file measures both:

  **A. IS IT FAITHFUL?**  A differential between the kernel's own compare and
     the platform's `strcasecmp`, over a domain no input file contains, WITH a
     must-fire mutant. `PROTOCOL_PHP.md` §A1(c): *"modelled by an equivalent" is
     a claim that needs a differential test, not a comment.*

  **B. WHAT DOES IT COST THE STATISTIC?**  Two builds of the SAME kernel — one
     with the compare in the kernel, one calling libc — measured under
     callgrind, reporting `kernel_exclusive_ir`, the whole-program total, and
     `inside_share` for each. ⭐ **Either answer is a result.** It prices F119's
     exclusion directly rather than arguing about it.

⚠⚠ **`inside_share` IS DEFINED HERE AND NOT INHERITED**, because the row must
say which number it divided by: it is `100 * (callgrind exclusive Ir of the
`kernel` symbol) / (callgrind `summary:` total Ir for the whole run)`, on the
SAME run. `.memory-php/03-numbers.md` requires it per CELL, so both variants are
measured at one opt level and one mode and the cell is named in the output.

⚠ **THE TWO BUILD DIRECTORIES HAVE EQUAL PATH LENGTHS BY CONSTRUCTION**
(`v00`, `v01`, asserted below). `RECAP_PHP.md` F101 / item 109: the kernel
fingerprint is PATH-SENSITIVE and has fired live in both directions on this
project, so a control that compared two binaries built under paths of different
lengths would be measuring its own directory names.

⚠ The compare's source is EXTRACTED FROM `c/kernel.c` BY TEXT rather than
retyped, so part A cannot drift from the shipped kernel. If the extraction
fails, the control fails loudly rather than testing a stale copy.
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PDIR = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(PDIR))
sys.path.insert(0, HERE)
import _pin  # noqa: E402

SCRATCH = os.path.join(REPO, ".temp", "php97", "libc")
GCC = "gcc"
VALGRIND = os.path.expanduser("~/tools/valgrind/bin/valgrind")
CG_ANNOTATE = os.path.expanduser("~/tools/valgrind/bin/callgrind_annotate")


# ------------------------------------------------------------------ extract --

def extract_compare():
    """`PH97_LOWER` and `ph97_strcasecmp`, lifted out of `c/kernel.c` by text.

    Brace-matched rather than regex-terminated: a regex that stopped at the
    first `}` would silently lift half a function and part A would then be
    testing something that is not in the kernel."""
    src = open(os.path.join(PDIR, "c", "kernel.c")).read()
    i = src.index("#define PH97_LOWER")
    j = src.index("static int ph97_strcasecmp", i)
    k = src.index("{", j)
    depth, e = 0, k
    while True:
        if src[e] == "{":
            depth += 1
        elif src[e] == "}":
            depth -= 1
            if depth == 0:
                break
        e += 1
    body = src[i:e + 1]
    assert body.count("{") == body.count("}"), "unbalanced extraction"
    assert "return (int) ca - (int) cb;" in body, "extraction missed the result"
    return body


# ------------------------------------------------- part A: the differential --

PROBE = r"""
/* GENERATED by controls/libc_compare.py -- do not edit; edit the generator. */
#define _GNU_SOURCE
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <strings.h>

%(compare)s

#ifdef PH97_MUTANT
/* MUST-FIRE control: a compare that is case-SENSITIVE. If the differential
 * reports ZERO disagreements for this, the differential is measuring nothing
 * and part A is worthless. */
static int ph97_probe(const char *a, const char *b) { return strcmp(a, b); }
#else
static int ph97_probe(const char *a, const char *b) { return ph97_strcasecmp(a, b); }
#endif

static int sgn(int x) { return x < 0 ? -1 : (x > 0 ? 1 : 0); }

int main(void)
{
    static const char *const sel[] = {
        "all", "internal_encoding", "http_input", "http_output",
        "func_overload", "", "al", "allx", "ALL", "AlL", "HtTp_InPuT",
        "nonesuch", "a", "zzz", "ALLL", "internal_encodinG", "1", "0",
        "http_inpu", "http_inputx", "FUNC_OVERLOAD", "Internal_Encoding"
    };
    const int n = (int) (sizeof sel / sizeof sel[0]);
    long tried = 0, disagree = 0;
    int i, j;
    char ba[32], bb[32];
    unsigned c;

    for (i = 0; i < n; i++) {
        for (j = 0; j < n; j++) {
            int x = sgn(ph97_probe(sel[i], sel[j]));
            int y = sgn(strcasecmp(sel[i], sel[j]));
            tried++;
            if (x != y) disagree++;
        }
    }
    /* every one-character mutation of every selector, over the whole byte
     * range -- 0 included, which is where a NUL-terminated compare and a
     * length-bounded one part company */
    for (i = 0; i < n; i++) {
        size_t L = strlen(sel[i]), p;
        for (p = 0; p < L; p++) {
            for (c = 0; c < 256; c++) {
                size_t q;
                for (q = 0; q < L && q < 30; q++) ba[q] = sel[i][q];
                ba[L < 30 ? L : 30] = '\0';
                ba[p] = (char) c;
                for (q = 0; q < L && q < 30; q++) bb[q] = sel[i][q];
                bb[L < 30 ? L : 30] = '\0';
                {
                    int x = sgn(ph97_probe(ba, bb));
                    int y = sgn(strcasecmp(ba, bb));
                    tried++;
                    if (x != y) disagree++;
                }
            }
        }
    }
    printf("%%ld %%ld\n", tried, disagree);
    return 0;
}
"""


def part_a():
    os.makedirs(SCRATCH, exist_ok=True)
    src = os.path.join(SCRATCH, "diff.c")
    open(src, "w").write(PROBE % {"compare": extract_compare()})
    out = {}
    for tag, flags in (("shipped", []), ("mutant", ["-DPH97_MUTANT"])):
        exe = os.path.join(SCRATCH, "diff-" + tag)
        subprocess.run([GCC, "-std=c99", "-O1", "-Wall", "-Wextra"] + flags
                       + [src, "-o", exe], check=True)
        r = subprocess.run([exe], capture_output=True, text=True, check=True)
        tried, dis = (int(x) for x in r.stdout.split())
        out[tag] = {"tried": tried, "disagreements": dis}
    return out


# -------------------------------------------------------- part B: the cost --

LIBC_PATCH = ("""/* SUBSTITUTED by controls/libc_compare.py: the compare is libc's. */
#include <strings.h>
#define ph97_strcasecmp strcasecmp
""")


def _variant(vdir, use_libc):
    """One build tree. ⚠ `vdir` is `vNN`, FIXED WIDTH -- see the module head."""
    d = os.path.join(SCRATCH, vdir)
    shutil.rmtree(d, ignore_errors=True)
    os.makedirs(os.path.join(d, "c"))
    for f in ("kernel.h", "main.c"):
        shutil.copy(os.path.join(PDIR, "c", f), os.path.join(d, "c", f))
    src = open(os.path.join(PDIR, "c", "kernel.c")).read()
    if use_libc:
        body = extract_compare()
        assert src.count(body) == 1
        src = src.replace(body, LIBC_PATCH, 1)
    open(os.path.join(d, "c", "kernel.c"), "w").write(src)
    shutil.copy(os.path.join(REPO, "common-php", "emalloc_shim.h"),
                os.path.join(d, "c", "emalloc_shim.h"))
    exe = os.path.join(d, "k")
    subprocess.run(
        [GCC, "-std=c99", "-O3", "-Wall", "-Wextra", "-DSLB_ISOLATED",
         "-I", os.path.join(REPO, "common"), "-I", os.path.join(d, "c"),
         os.path.join(REPO, "common", "driver.c"),
         os.path.join(d, "c", "kernel.c"), os.path.join(d, "c", "main.c"),
         "-o", exe], check=True)
    return exe


_CG_ROW = re.compile(r"^\s*([\d,]+)\s+(.*)$")


def _cg(exe, inp, tag):
    out = os.path.join(SCRATCH, f"cg.{tag}.out")
    r = subprocess.run([VALGRIND, "--tool=callgrind",
                        f"--callgrind-out-file={out}", exe, inp],
                       capture_output=True, text=True)
    if r.returncode != 0:
        return {"error": f"callgrind exit {r.returncode}"}
    total = None
    for line in open(out):
        if line.startswith("summary:") or line.startswith("totals:"):
            total = int(line.split(":", 1)[1].strip().split()[0])
    ann = subprocess.run([CG_ANNOTATE, "--threshold=100", out],
                         capture_output=True, text=True).stdout
    kern = 0
    seen = []
    for line in ann.splitlines():
        m = _CG_ROW.match(line)
        if not m or ":" not in m.group(2):
            continue
        func = m.group(2).split(":", 1)[1].split(" [")[0].strip()
        if re.search(r"(?:^|::)kernel(?:$|[^A-Za-z0-9_])", func):
            kern += int(m.group(1).replace(",", ""))
            seen.append(func)
    return {"kernel_exclusive_ir": kern or None, "kernel_functions": sorted(set(seen)),
            "whole_program_ir": total,
            "inside_share_pct": (100.0 * kern / total) if (kern and total) else None}


def part_b():
    v0 = _variant("v00", use_libc=False)
    v1 = _variant("v01", use_libc=True)
    assert len(os.path.dirname(v0)) == len(os.path.dirname(v1)), (
        "the two build directories must have EQUAL PATH LENGTHS (F101)")
    inp = os.path.join(PDIR, "inputs", "small.bin")
    res = {}
    for tag, exe in (("in-kernel", v0), ("libc", v1)):
        got = subprocess.run([exe, inp], capture_output=True, text=True)
        res[tag] = {"checksum": got.stdout.strip(), "exit": got.returncode}
        res[tag].update(_cg(exe, inp, tag))
    res["checksums_agree"] = (res["in-kernel"]["checksum"]
                              == res["libc"]["checksum"])
    return res


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--no-cost", action="store_true",
                    help="part A only -- seconds rather than minutes")
    a = ap.parse_args()

    problems = []
    rec = {"cell": "c-gcc O3 isolated, small.bin",
           "inside_share_definition":
               "100 * callgrind exclusive Ir of the `kernel` symbol / callgrind "
               "`summary:` total Ir for the same run"}

    print("A. IS THE IN-KERNEL COMPARE FAITHFUL? (differential vs libc "
          "strcasecmp, with a must-fire mutant)")
    rec["differential"] = part_a()
    s, m = rec["differential"]["shipped"], rec["differential"]["mutant"]
    print(f"   shipped  : {s['disagreements']:6d} disagreements in "
          f"{s['tried']} comparisons")
    print(f"   MUTANT   : {m['disagreements']:6d} disagreements in "
          f"{m['tried']} comparisons   (must be > 0)")
    if s["disagreements"] != 0:
        problems.append(f"the shipped compare disagrees with libc strcasecmp on "
                        f"{s['disagreements']} of {s['tried']} comparisons -- "
                        f"spec.md declares the substitution behaviour-preserving")
    if m["disagreements"] <= 0:
        problems.append("the MUST-FIRE mutant (a case-SENSITIVE compare) agrees "
                        "with libc everywhere, so the differential is measuring "
                        "nothing and part A certifies nothing")

    if not a.no_cost:
        print("\nB. WHAT DOES THE SUBSTITUTION COST THE STATISTIC? "
              "(F119's exclusion, priced)")
        rec["cost"] = part_b()
        for tag in ("in-kernel", "libc"):
            c = rec["cost"][tag]
            print(f"   {tag:10s} A1={c.get('kernel_exclusive_ir')}  "
                  f"W={c.get('whole_program_ir')}  "
                  f"inside_share={c.get('inside_share_pct')}  "
                  f"fns={c.get('kernel_functions')}")
        if not rec["cost"]["checksums_agree"]:
            problems.append("the two variants return DIFFERENT checksums, so "
                            "they are not the same program and the cost "
                            "comparison means nothing")
        ik = rec["cost"]["in-kernel"].get("inside_share_pct")
        lc = rec["cost"]["libc"].get("inside_share_pct")
        if ik is not None and lc is not None:
            print(f"\n   ⭐ inside_share moves {ik:.2f} % -> {lc:.2f} % when the "
                  f"compare leaves the measured symbol "
                  f"({lc - ik:+.2f} pp). EITHER ANSWER IS A RESULT.")
            rec["cost"]["inside_share_delta_pp"] = lc - ik

    rec["problems"] = problems
    rec.update(_pin.pin(["c/kernel.c", "c/main.c", "c/kernel.h",
                         "inputs/small.bin"],
                        "python3 controls/libc_compare.py",
                        "part A is seconds; part B runs callgrind twice"))
    with open(os.path.join(HERE, "libc_compare.json"), "w") as f:
        json.dump(rec, f, indent=1)
        f.write("\n")
    print(f"\nwrote controls/libc_compare.json -- {len(problems)} problem(s)")
    for p in problems:
        print("  ⛔ " + p)
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
