#!/bin/sh
# =============================================================================
# sweep_cg.sh -- THE GENERATOR FOR F83's AND F84's PROFILES
#
# ⛔⛔ WHY THIS FILE IS COMMITTED, AND IT IS NOT TIDINESS. It was written under
# `.temp/mgr172/`, which is GITIGNORED, and it is the ONLY thing that rebuilds
# the input `.tasks-php/probes/bc_sweep.py` (**F84**) and
# `.tasks-php/probes/inclusive_ir.py` (**F83**) read. ▶ A PUBLISHED FINDING
# WHOSE ONLY EVIDENCE IS A GITIGNORED PROBE IS A FINDING THAT WILL NOT SURVIVE A
# CLEAN CHECKOUT -- `.memory-php/04-process.md` LAW 11 -- and **promoting those
# two probes while leaving THIS in deletable scratch would not survive one
# either**: their evidence would be committed and un-regenerable.
#
# ⚠⚠ NOTE WHAT IS AND IS NOT THE DEFECT. The PROFILES it writes stay under
# `.temp/mgr172/cg/` and that is CORRECT -- CLAUDE.md constraint 6 is *keep the
# generator, delete the artefact*, and this file IS the generator. Committing
# 2 MB of `.out` blobs would be the defect, not the repair.
#
# RUN IT:  sh .tasks-php/probes/sweep_cg.sh
#
# ⛔ WHAT IT NEEDS THAT IS *NOT* COMMITTED, stated rather than discovered:
#   1. the built binaries under `.temp/php-root/.temp/build/<row>/` (GITIGNORED;
#      `python3 harness-php/gate.py --tool build <row> --all`);
#   2. valgrind at `$HOME/tools/valgrind/bin/valgrind` -- the PINNED build, not
#      the system one (`TOOLCHAIN.md`);
#   3. ⛔⛔ `R` BELOW IS A HARDCODED ABSOLUTE PATH TO THIS MACHINE'S CHECKOUT.
#      It is left exactly as written -- it is what produced every committed
#      profile, and `probes/rebuild_hardened_php.sh` already carries the same
#      shape -- but a reader on a different checkout MUST edit that one line.
#      ⚠ IT IS NOT DERIVED FROM `$0`, so this script does not follow its own
#      directory. Reported, not silently repaired.
# It WRITES only under `.temp/mgr172/cg/`. Committed inputs are read-only here.
# =============================================================================
# THE ONE REGENERATION ENTRY POINT for every callgrind profile under
# .temp/mgr172/cg/. Discharges CLAUDE.md constraint 6: a blob with no script
# that rebuilds it is the thing that may not be deleted.
#
# Covers: the R4/R5 pair of every PHP row except ph45, both measured inputs,
# O3/isolated; plus the ENVIRONMENT CONTROL that rules out check.py's
# stack-alignment mechanism as the cause of F83's +265.924.
#
# ⛔ ph45 IS DELIBERATELY EXCLUDED while TASK_PHP_037 rebuilds it -- its
# binaries could move mid-sweep. Re-add it (and to
# `.tasks-php/probes/bc_sweep.py`'s ROWS) after that task lands, then re-run
# both. ⚠ TASK_PHP_037 HAS SINCE LANDED, so this exclusion is now a STANDING
# GAP rather than a live precaution: F84's table is 12 cells over 6 rows and
# ph45 is not one of them. Re-adding it is a measurement, not an edit.
# ⚠ p25-realloc-growth (PAT) is regenerated by
# `.tasks-php/probes/inclusive_ir.py --regen`, which also md5-verifies the
# binaries first. Run that too. ⛔ That flag does NOT write the `envctl.*`
# control -- only this script does.
#
# Existing .out files are SKIPPED, so this is safe to re-run.
set -u
R=/home/apt/repos_common/sec-ladder
V=$HOME/tools/valgrind/bin/valgrind
mkdir -p "$R/.temp/mgr172/cg"

run() {   # run <outfile> <binary> <input> [envpad]
  out=$1; bin=$2; inp=$3
  [ -f "$out" ] && { echo "skip $(basename "$out")"; return; }
  if [ $# -ge 4 ]; then
    MGRPAD=$(python3 -c "print('x'*$4)") timeout 1200 "$V" --tool=callgrind \
      --callgrind-out-file="$out" "$bin" "$inp" >/dev/null 2>&1
  else
    timeout 1200 "$V" --tool=callgrind \
      --callgrind-out-file="$out" "$bin" "$inp" >/dev/null 2>&1
  fi
  [ -f "$out" ] && echo "ok   $(basename "$out")" || echo "FAIL $(basename "$out")"
}

for pair in ph00:ph00-smoke ph03:ph03-uudecode-bound ph07:ph07-strcut-cursor \
            ph16:ph16-fdset-index ph29:ph29-recvfrom-alloc \
            ph64:ph64-callback-frees-cursor; do
  row=${pair%%:*}; slug=${pair#*:}
  for cell in unsafe verus; do
    for inp in small large; do
      run "$R/.temp/mgr172/cg/$row.$cell.$inp.out" \
          "$R/.temp/php-root/.temp/build/$row/$cell-O3-isolated" \
          "$R/patterns-php/$slug/inputs/$inp.bin"
    done
  done
done

# THE ENVIRONMENT CONTROL. ONE binary, ONE input, three environment sizes.
# check.py documents that the environment block shifts the stack pointer and
# moves a per-call stack array's alignment by +-7. If that were F83's mechanism
# these three would differ. They do not: kernel inclusive is 181,733,873 at all
# three, spread 0. (`.tasks-php/probes/bc_sweep.py` has no negative for this;
# `.tasks-php/probes/inclusive_ir.py`'s N6 does -- and that N6 is why the
# `envctl.*` files are in inclusive_ir's required-input set.)
for pad in 0 200 4000; do
  run "$R/.temp/mgr172/cg/envctl.$pad.out" \
      "$R/.temp/php-root/.temp/build/ph03/unsafe-O3-isolated" \
      "$R/patterns-php/ph03-uudecode-bound/inputs/small.bin" "$pad"
done
echo "SWEEP DONE"

# ---- ph29 CROSS-LANGUAGE cells, added for the family-C re-derivation of the
# flip list (STATISTIC-DECISION-DRAFT.md §5 -- ⛔ UNCOMMITTED SCRATCH, it lives
# at `.temp/mgr172/STATISTIC-DECISION-DRAFT.md`, is GITIGNORED and was not
# promoted; the committed successor is `.tasks-php/STATISTICS_001.md`).
# ⚠ These 8 cells are written by this script and read by NEITHER promoted probe
# -- `bc_sweep.py` reads only the `unsafe`/`verus` pair -- so they are not in
# either probe's required-input set. ph29 carries the largest flips in
# the corpus and every one of them is measured against family B, which F84
# showed is confounded by up to ~17% of THIS row's marginal. Re-run them.
for cell in c-gcc c-clang safe_naive safe_tuned; do
  for inp in small large; do
    run "$R/.temp/mgr172/cg/ph29.$cell.$inp.out" \
        "$R/.temp/php-root/.temp/build/ph29/$cell-O3-isolated" \
        "$R/patterns-php/ph29-recvfrom-alloc/inputs/$inp.bin"
  done
done
echo "PH29 CROSS-LANGUAGE DONE"
