#!/usr/bin/env python3
"""p25 CONTROLS: **the THIRD C arm -- the unconditional re-derive -- built and
priced against R1 and R1h.**

    python3 patterns/p25-realloc-growth/controls/rederive.py

⚠⚠ **WHY THIS ARM EXISTS, AND IT IS THIS ROW'S SHARPEST C-SIDE FINDING.** The
shipped hardened cell guards the stale dereference with `curbase == toks` and
re-derives when the guard fails. **That guard is what every C programmer writes
and it is NOT sufficient under the C standard**: C99 7.20.3.4p4 / C11 7.22.3.5p4
with DR 400 make the old pointer value indeterminate the moment `realloc`
returns, *whether or not the block moved*, so the surviving `*cur` in the true
branch is a use of an indeterminate value under the abstract machine even though
no relocating allocator can observe it.

**The standard-clean rung never dereferences `cur` at all** -- it re-derives
`toks[curi]` unconditionally. That is precisely the ADDRESSING-MODE CHANGE
`TASK_134`'s kill named, so this control is where both halves of that kill get
answered and they go opposite ways: the conjunct EXISTS (`safety_line.py`
measures the shipped diff) and it is INSUFFICIENT (this file builds what is
sufficient and prices it).

⚠ **THE ARM IS GENERATED BY SUBSTITUTION AND THE SUBSTITUTION COUNT IS
ASSERTED.** `p28d` shipped an uninitialised pointer because a `str.replace()`
silently matched nothing (`CLAUDE.md` rule 1). One statement in the SHIPPED
`../c/kernel.c` is rewritten -- `v = (uint64_t)*cur;` becomes
`v = (uint64_t)toks[curi];` -- and the count must be exactly 1 or this script
exits before compiling anything.

WHAT IT MEASURES
----------------
  * **correctness**: the re-derive arm's checksum on every shipped input, against
    `../model.py`. It must agree on ALL of them -- benign AND adversarial --
    because it is the standard-clean rung;
  * **the detector**: ASan and UBSan on every input; the arm must be CLEAN
    everywhere, exactly as R1h is;
  * **static cost**: non-pad instruction count of the `kernel` symbol for R1,
    R1h and the re-derive arm, at `-O0` and `-O3`, gcc and clang;
  * **dynamic cost**: marginal `Ir` per kernel call, `(Ir@200 - Ir@100) / 100`,
    on `small.bin` and `large.bin`, at `-O0` and `-O3`, with the PINNED
    callgrind. ⚠ Two runs of the same binary, so the one-shot loader terms
    cancel; `.memory/03-measurement.md`'s rule.

⚠ **NAME THE WEAKER-SEARCHED ENDPOINT** (`TASK_157` deliverable 4). Neither the
shipped R1h nor this arm has had its spelling searched: each is ONE spelling of
its repair, chosen for readability. The figure below is *"the cost of THESE two
spellings"* and never *"the cost of the repair"*.
"""

import glob
import hashlib
import json
import os
import re
import struct
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
PDIR = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(PDIR))
COMMON = os.path.join(REPO, "common")
CDIR = os.path.join(PDIR, "c")
INDIR = os.path.join(PDIR, "inputs")
TMP = os.path.join(REPO, ".temp", "p25ctl")

GCC = os.environ.get("SLB_GCC", "/usr/bin/gcc")
CLANG = os.environ.get("SLB_CLANG", os.path.expanduser("~/tools/llvm/bin/clang"))
VALGRIND = os.path.expanduser("~/tools/valgrind/bin/valgrind")
CG_ANNOTATE = os.path.expanduser("~/tools/valgrind/bin/callgrind_annotate")

sys.path.insert(0, PDIR)
sys.path.insert(0, os.path.join(REPO, "harness"))
import model as m25  # noqa: E402
import asm as asmmod  # noqa: E402

# ⚠ ANCHORED ON THE NEWLINE AND THE INDENT. The bare statement text occurs
# TWICE in c/kernel.c -- once as code and once inside the comment that spells
# out what the hardened rung writes -- and the first version of this control
# asserted a count of 1 and REFUSED TO BUILD, which is the guard working. The
# anchored form matches the code line and only the code line.
OLD = "\n                v = (uint64_t)*cur;\n"
NEW = "\n                v = (uint64_t)toks[curi];\n"
_CG_ROW = re.compile(r"^\s*([\d,]+)\s+(.*)$")


def make_arm():
    """`../c/kernel.c` with the ONE dereference replaced by the re-derive."""
    src = open(os.path.join(CDIR, "kernel.c")).read()
    n = src.count(OLD)
    if n != 1:
        raise SystemExit(
            f"rederive.py: the substitution `{OLD}` matched {n} time(s) in "
            f"c/kernel.c, not 1. REFUSING to build -- a str.replace() that "
            f"silently matches nothing is how p28d shipped an uninitialised "
            f"pointer (CLAUDE.md rule 1).")
    body = src.replace(OLD, NEW)
    hdr = ("/* GENERATED by controls/rederive.py from ../c/kernel.c by ONE\n"
           " * substitution of the READ statement. Do not edit; edit the\n"
           " * generator.\n"
           " * THIS IS THE STANDARD-CLEAN RUNG: it never dereferences `cur`,\n"
           " * so DR 400's indeterminate-pointer rule cannot reach it. */\n")
    out = os.path.join(TMP, "kernel_rederive.c")
    open(out, "w").write(hdr + body)
    return out, n


def build(cc, kern, opt, tag, extra=()):
    out = os.path.join(TMP, f"rd_{tag}")
    cmd = [cc, "-std=c99", f"-{opt}", "-I", COMMON, "-I", CDIR] + list(extra) + [
        "-o", out, kern, os.path.join(CDIR, "main.c"),
        os.path.join(COMMON, "driver.c")]
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=900)
    if r.returncode != 0:
        raise SystemExit(f"rederive.py: build failed ({tag}):\n{r.stderr}")
    return out


def env_clean():
    e = dict(os.environ)
    e.pop("LD_PRELOAD", None)
    e["ASAN_OPTIONS"] = "detect_leaks=0"
    return e


def run(binary, arg):
    r = subprocess.run([binary, arg], capture_output=True, text=True,
                       timeout=900, env=env_clean())
    return r.returncode, r.stdout.strip(), " ".join(r.stderr.split())


def iters_copy(name, iters):
    src = os.path.join(INDIR, name)
    blob = open(src, "rb").read()
    _n, decl = struct.unpack("<QQ", blob[:16])
    dst = os.path.join(TMP, f"it{iters}_{name}")
    with open(dst, "wb") as f:
        f.write(struct.pack("<QQ", iters, decl))
        f.write(blob[16:])
    return dst


def kernel_ir(binary, blob, tag):
    out = os.path.join(TMP, f"cg.{tag}.out")
    r = subprocess.run([VALGRIND, "--tool=callgrind",
                        f"--callgrind-out-file={out}", binary, blob],
                       capture_output=True, text=True, timeout=3600,
                       env=env_clean())
    if r.returncode != 0:
        return None
    ann = subprocess.run([CG_ANNOTATE, "--threshold=100", out],
                         capture_output=True, text=True, timeout=3600).stdout
    total = None
    for line in ann.splitlines():
        m = _CG_ROW.match(line)
        if not m or ":" not in m.group(2):
            continue
        func = m.group(2).split(":", 1)[1].split(" [")[0].strip()
        if re.search(r"(?:^|::)kernel(?:$|[^A-Za-z0-9_])", func):
            total = (total or 0) + int(m.group(1).replace(",", ""))
    os.unlink(out)
    return total


def derived_from():
    out = {}
    for rel in ("patterns/p25-realloc-growth/c/kernel.c",
                "patterns/p25-realloc-growth/c/kernel_hardened.c",
                "patterns/p25-realloc-growth/c/main.c",
                "patterns/p25-realloc-growth/model.py",
                "patterns/p25-realloc-growth/inputs/gen.py",
                "patterns/p25-realloc-growth/controls/rederive.py",
                "common/driver.c"):
        p = os.path.join(REPO, rel)
        out[rel] = hashlib.sha256(open(p, "rb").read()).hexdigest()
    return out


def main():
    os.makedirs(TMP, exist_ok=True)
    arm, nsub = make_arm()
    print(f"  generated {os.path.relpath(arm, REPO)} by {nsub} substitution")
    problems = []

    kernels = {"R1": os.path.join(CDIR, "kernel.c"),
               "R1h": os.path.join(CDIR, "kernel_hardened.c"),
               "rederive": arm}

    # ---- correctness + detectors on the re-derive arm --------------------
    print("\nA. correctness and detectors, re-derive arm, gcc -O1")
    ck = {}
    inputs = sorted(f for f in os.listdir(INDIR)
                    if f.endswith(".bin") and not f.startswith("sweep-"))
    plain = build(GCC, arm, "O1", "plain_rd")
    asan = build(GCC, arm, "O1", "asan_rd",
                 ("-fsanitize=address", "-fno-omit-frame-pointer"))
    ubsan = build(GCC, arm, "O1", "ubsan_rd",
                  ("-fsanitize=undefined", "-fno-sanitize-recover=all",
                   "-fstrict-aliasing"))
    for name in inputs:
        mod = m25.build(os.path.join(INDIR, name))
        rc, so, _ = run(plain, os.path.join(INDIR, name))
        _rc2, _so2, se2 = run(asan, os.path.join(INDIR, name))
        _rc3, _so3, se3 = run(ubsan, os.path.join(INDIR, name))
        fired = ("AddressSanitizer" in se2) or ("runtime error:" in se3)
        ck[name] = {"stdout": so, "model": str(mod.checksum), "fired": fired}
        ok = so == str(mod.checksum)
        print(f"     {name:26s} {so:24s} model {mod.checksum!s:24s} "
              f"{'OK' if ok else 'DIFFERS'}  sanitizer={'FIRED' if fired else 'clean'}")
        if not ok:
            problems.append(
                f"{name}: the re-derive arm printed {so}, model says "
                f"{mod.checksum}. It is supposed to be the STANDARD-CLEAN rung, "
                f"so it must agree on every input, adversarial included")
        if fired:
            problems.append(
                f"{name}: a sanitizer fired on the re-derive arm "
                f"({se2[:120]} {se3[:120]}). It never dereferences `cur`, so "
                f"there is nothing for a detector to see")

    # ---- static cost -----------------------------------------------------
    print("\nB. static instruction count of the `kernel` symbol")
    static = {}
    for cc, ccname in ((GCC, "gcc"), (CLANG, "clang")):
        if not os.path.exists(cc) and not cc.startswith("/usr"):
            continue
        for opt in ("O0", "O3"):
            for arm_name, kern in kernels.items():
                b = build(cc, kern, opt, f"st_{ccname}_{opt}_{arm_name}",
                          ("-DSLB_ISOLATED",))
                k = asmmod.kernel(b, "kernel")
                static[f"{ccname}/{opt}/{arm_name}"] = {
                    "n_fn_nopad": k.n_fn_nopad, "fn_bytes": len(k.fn_bytes)}
                os.unlink(b)
        for opt in ("O0", "O3"):
            r1 = static[f"{ccname}/{opt}/R1"]["n_fn_nopad"]
            r1h = static[f"{ccname}/{opt}/R1h"]["n_fn_nopad"]
            rd = static[f"{ccname}/{opt}/rederive"]["n_fn_nopad"]
            print(f"     {ccname:6s} {opt}  R1 {r1:5d}   R1h {r1h:5d} "
                  f"({r1h - r1:+d})   rederive {rd:5d} ({rd - r1:+d} vs R1, "
                  f"{rd - r1h:+d} vs R1h)")

    # ---- dynamic cost ----------------------------------------------------
    print("\nC. marginal Ir per kernel call, (Ir@200 - Ir@100)/100, gcc, isolated")
    marg = {}
    for inp in ("small.bin", "large.bin"):
        b100, b200 = iters_copy(inp, 100), iters_copy(inp, 200)
        for opt in ("O0", "O3"):
            for arm_name, kern in kernels.items():
                b = build(GCC, kern, opt, f"cg_{opt}_{arm_name}",
                          ("-DSLB_ISOLATED",))
                i100 = kernel_ir(b, b100, f"{inp}_{opt}_{arm_name}_100")
                i200 = kernel_ir(b, b200, f"{inp}_{opt}_{arm_name}_200")
                marg[f"{inp}/{opt}/{arm_name}"] = (
                    None if i100 is None or i200 is None
                    else (i200 - i100) / 100.0)
                os.unlink(b)
            r1 = marg[f"{inp}/{opt}/R1"]
            r1h = marg[f"{inp}/{opt}/R1h"]
            rd = marg[f"{inp}/{opt}/rederive"]
            if None not in (r1, r1h, rd):
                print(f"     {inp:10s} {opt}  R1 {r1:10.2f}   "
                      f"R1h {r1h:10.2f} ({r1h - r1:+8.2f}, "
                      f"{100 * (r1h - r1) / r1:+6.2f}%)   "
                      f"rederive {rd:10.2f} ({rd - r1:+8.2f}, "
                      f"{100 * (rd - r1) / r1:+6.2f}%)")
        os.unlink(b100)
        os.unlink(b200)

    doc = {"pin": {"regenerate": "python3 patterns/p25-realloc-growth/controls/"
                                 "rederive.py"},
           "derived_from_sha256": derived_from(),
           "measured_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
           "substitution": {"from": OLD, "to": NEW, "count": nsub},
           "checksums": ck,
           "static_kernel_insns": static,
           "marginal_ir_per_call": marg,
           "problems": problems,
           "invariant": "The UNCONDITIONAL re-derive -- the only C rung that DR "
                        "400 cannot reach, because it never dereferences `cur` "
                        "-- agrees with model.py on EVERY input including the "
                        "adversarial ones, is sanitizer-clean everywhere, and "
                        "its static and marginal costs are recorded beside R1's "
                        "and R1h's at both optimisation levels. ⚠ Neither "
                        "repair's SPELLING has been searched; the figures are "
                        "the cost of THESE two spellings, never of 'the "
                        "repair'."}
    out = os.path.join(HERE, "rederive.json")
    json.dump(doc, open(out, "w"), indent=2)
    print(f"\nwrote {out}")
    for p in problems:
        print(f"  *** {p}", file=sys.stderr)
    for f in [plain, asan, ubsan] + glob.glob(os.path.join(TMP, "it*_*.bin")):
        if os.path.exists(f):
            os.unlink(f)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
