#!/usr/bin/env python3
"""ph66 control -- ⭐⭐⭐ THE OBLIGATION THIS ROW'S DEFECT ACTUALLY VIOLATES,
BUILT IN VERUS TWICE: once against the HARDENED predicate, where it verifies,
and once against the SHIPPED one, where it does not.

    python3 patterns-php/ph66-hashdel-uncompared/controls/key_identity.py
    python3 patterns-php/ph66-hashdel-uncompared/controls/key_identity.py --selftest

============================================================================
WHY THIS FILE EXISTS -- AND IT IS NOT DECORATION
============================================================================
`../verus.rs` proves `kernel` returns `hash_fold(...)`. That is a VALUE
postcondition against a spec function which ITSELF CARRIES THE DEFECT, so R5
verifies with `zend_hash.c:464`'s disjunct in place -- as every rung below R1h
on this row does. Read on its own, that reads as *"Verus does not see this
defect either"*, and it would be the wrong reading.

▶ **The property that excludes the defect is not a refcount property and not a
memory-safety property. It is the corpus's own labeller's, written in
`paper/_old_story/invariants-166.json` `cases[98]`, quoted verbatim:**

  > *The true primary is arguably a NEW entry:* `NEW:container-key-identity` --
  > *"a hash-table operation acts on the bucket whose key equals the requested
  > key in both key kind and key bytes, and on no other bucket"* -- *which by
  > the restatement test is T1-universal (no PHP noun) and construct-bound (a
  > single defective predicate at `zend_hash.c:464`; every sibling lookup in the
  > same file is correct). I did not file it as the label because the rule says
  > NEW only if genuinely nothing fits.*

This file states exactly that, as a Verus `ensures` on the chain walk:

    r != NIL ==> a[r].nkl == nkl && (nkl == 0 || a[r].k == k)

*the bucket the walk selects has the requested key KIND (`nKeyLength`), and --
when a key was named at all -- the requested key BYTES.*

⭐ It VERIFIES against `b73349dbe4e9`'s predicate and FAILS against 5.0.0's.
That is the whole of this row's R5 result, and it is measured rather than
argued. ../NOTES.md sections 6 and 7.

============================================================================
⛔ THE THREE ARMS, AND WHY A TWO-ARM VERSION WOULD PROVE NOTHING (`§H`)
============================================================================
  N1  HARDENED + the obligation      -> must VERIFY
  N2  SHIPPED  + the obligation      -> must FAIL, with a POSTCONDITION error
                                        (a syntax or type error would pass a
                                        naive "did it fail?" test while
                                        measuring nothing)
  N3  SHIPPED  + a VACUOUS obligation -> must VERIFY. Without N3 the whole file
                                        is consistent with "Verus refuses this
                                        shape of file", and the difference
                                        between N1 and N2 would not be
                                        attributable to the PREDICATE.
"""

import argparse
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROW = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(ROW))
WORK = os.path.join(REPO, ".temp", "ph66-controls")
sys.path.insert(0, HERE)
import _pin  # noqa: E402

#: `zend_hash.c:464-465` as shipped -- the key KIND is settled by a DISJUNCT.
PRED_SHIPPED = ("a[p as int].h == h && (a[p as int].nkl == 0 "
                "|| (a[p as int].nkl == nkl && a[p as int].k == k))")
#: `b73349dbe4e9`'s predicate -- the length test hoisted into a REQUIRED
#: conjunct, so the surviving `== 0` disjunct only short-circuits the memcmp.
PRED_HARDENED = ("a[p as int].h == h && a[p as int].nkl == nkl "
                 "&& (a[p as int].nkl == 0 || a[p as int].k == k)")

#: The obligation. `KEY_IDENTITY` is the labeller's property; `VACUOUS` is N3's
#: control, which asserts nothing about which bucket was chosen.
OBL_KEY_IDENTITY = (
    "r != NIL ==> ((r as int) < a.len() && a[r as int].nkl == nkl "
    "&& (nkl == 0 || a[r as int].k == k))")
OBL_VACUOUS = "r == NIL || r != NIL"

TEMPLATE = r"""// GENERATED by controls/key_identity.py -- do not edit, regenerate.
// predicate: %(pname)s      obligation: %(oname)s
use vstd::prelude::*;

verus! {

pub const NIL: u32 = 0xFFFF_FFFF;

pub struct Node {
    pub h: u64,
    pub nkl: u32,
    pub k: u64,
    pub nxt: u32,
}

/// `zend_hash_del_key_or_index`'s chain walk, zend_hash.c:463-465.
pub open spec fn find(a: Seq<Node>, p: u32, h: u64, nkl: u32, k: u64, fuel: nat) -> u32
    decreases fuel,
{
    if fuel == 0 || p == NIL || p as int >= a.len() {
        NIL
    } else if %(pred)s {
        p
    } else {
        find(a, a[p as int].nxt, h, nkl, k, (fuel - 1) as nat)
    }
}

/// ⭐ THE OBLIGATION: the bucket deleted is the bucket named, in kind and in
/// bytes. `NEW:container-key-identity`, in the corpus labeller's own words.
pub proof fn key_identity(a: Seq<Node>, p: u32, h: u64, nkl: u32, k: u64, fuel: nat)
    ensures
        ({
            let r = find(a, p, h, nkl, k, fuel);
            %(obl)s
        }),
    decreases fuel,
{
    if fuel == 0 || p == NIL || p as int >= a.len() {
    } else if %(pred)s {
    } else {
        key_identity(a, a[p as int].nxt, h, nkl, k, (fuel - 1) as nat);
    }
}

fn main() {}

} // verus!
"""

ARMS = [
    ("N1", "hardened", PRED_HARDENED, "key-identity", OBL_KEY_IDENTITY, True),
    ("N2", "shipped", PRED_SHIPPED, "key-identity", OBL_KEY_IDENTITY, False),
    ("N3", "shipped", PRED_SHIPPED, "vacuous", OBL_VACUOUS, True),
]


def run_arm(pname, pred, oname, obl):
    os.makedirs(WORK, exist_ok=True)
    src = os.path.join(WORK, f"key_identity_{pname}_{oname.replace('-', '_')}.rs")
    with open(src, "w") as f:
        f.write(TEMPLATE % {"pname": pname, "oname": oname, "pred": pred,
                            "obl": obl})
    r = subprocess.run([os.path.join(REPO, "verus_run.py"), src,
                        "--crate-type=lib"],
                       capture_output=True, text=True, timeout=900)
    out = r.stdout + r.stderr
    m = re.search(r"(\d+) verified, (\d+) errors", out)
    verified = m and int(m.group(2)) == 0
    postcond = "postcondition not satisfied" in out
    return verified, postcond, out


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--verbose", action="store_true")
    a = ap.parse_args()

    bad = []
    rec = {"arms": {}, "problems": bad}
    for arm, pname, pred, oname, obl, want_ok in ARMS:
        ok, postcond, out = run_arm(pname, pred, oname, obl)
        good = (ok == want_ok)
        if arm == "N2":
            # ⛔ "it failed" is not enough: it must have failed on the
            # POSTCONDITION, or the arm is measuring a typo.
            good = good and postcond
        print(f"  {'PASS' if good else 'FAIL'}  {arm}  predicate={pname:<9} "
              f"obligation={oname:<12} -> "
              f"{'VERIFIES' if ok else 'FAILS'}"
              f"{' (postcondition)' if postcond else ''}"
              f"   [want {'VERIFIES' if want_ok else 'FAILS'}]")
        if a.verbose or not good:
            tail = "\n".join(out.strip().splitlines()[-12:])
            print("        " + tail.replace("\n", "\n        "))
        rec["arms"][arm] = {"predicate": pname, "obligation": oname,
                            "verifies": ok, "postcondition_failure": postcond,
                            "want_verifies": want_ok, "ok": good}
        if not good:
            bad.append(arm)

    rec.update(_pin.pin(["c/kernel.c", "c/kernel_hardened.c", "verus.rs"],
                        "python3 controls/key_identity.py",
                        "three Verus runs; about a minute"))
    with open(os.path.join(HERE, "key_identity.json"), "w") as f:
        json.dump(rec, f, indent=1)
        f.write("\n")
    print()
    if bad:
        print("SELFTEST FAIL: " + " ".join(bad))
        return 1
    print("SELFTEST PASS -- and the READING is the point:\n"
          "  ⭐ Verus CAN state `NEW:container-key-identity`, it DOES discharge\n"
          "     it against b73349dbe4e9's predicate, and it REFUSES it against\n"
          "     PHP 5.0.0's. R5 is therefore the only rung on this row that can\n"
          "     refuse the defect -- but ONLY when the obligation is stated as a\n"
          "     KEY-IDENTITY property. `../verus.rs`'s shipped `ensures` is a\n"
          "     value postcondition against a spec function that carries the\n"
          "     defect, so it verifies WITH the defect in place. Both halves are\n"
          "     the row's result and ../NOTES.md section 7 states both.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
