#!/usr/bin/env python3
"""Does "the guard fired" force an out-of-bounds store? Only for one threshold.

    python3 patterns/p12-strcat-fixed/controls/threshold_probe.py

**Why this exists.** TASK_040_REVIEW retracted p12's "a row on which a write bug
fires cannot also be a checksum-agreeing row" and replaced it with a half that
*is* forced (`../NOTES.md` 1a, `.memory/02-bench-rules.md`):

> for a write bug whose guard's threshold is the destination's allocated extent,
> every input on which the guard fires is one on which the unguarded rung
> executes an out-of-bounds store.

**p13, p14, p23, p24 and p25 were told to inherit that**, so the premise had
better be load-bearing rather than decorative. This probe holds *everything*
fixed except the guard's threshold:

    lim = guard ? min(slen, n) : slen;     dst[128], one NUL-terminated string

  * `n = 128 == sizeof dst` — p12's shape. The guard fires and the unguarded
    copy stores out of bounds.
  * `n = 64  <  sizeof dst` — `strncpy`'s shape, where `n` is a **caller's**
    parameter. The guard fires just as loudly, the two checksums differ, and the
    unguarded copy is **entirely in bounds**.

So divergence is not the discriminator and the write is not the discriminator;
**the threshold is**. p13's `n` is caller-supplied and p24's `child < n` is a
live length below capacity, so neither inherits the sentence; p23's and p25's
guards are the allocation's own extent, so they do.

Needs `~/tools/llvm/bin/clang`; nothing else. The `.c` and the binary land in
`.temp/p12/controls/` and are re-derivable from this file.
"""
import os
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.abspath(__file__)))))
OUT = os.path.join(REPO, ".temp", "p12", "controls")
CLANG = os.path.expanduser("~/tools/llvm/bin/clang")

SRC = r"""/* GENERATED by patterns/p12-strcat-fixed/controls/threshold_probe.py.
 * Everything is held fixed except the guard's THRESHOLD `n`. */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define DST_CAP 128

static uint8_t src[512];

/* p13's shape: copy at most `n` bytes of a NUL-terminated string, where `n` is
 * a parameter and not `sizeof dst`.  `guard == 0` deletes the clamp, which is
 * the same one-line deletion that turns p12's R1h into R1. */
__attribute__((noinline))
static uint64_t kern(const uint8_t *w, size_t len, size_t n, int guard)
{
    uint8_t dst[DST_CAP];
    size_t q = 0, i, lim, slen, dlen = 0;
    uint64_t acc = 0;

    memset(dst, 0, DST_CAP);
    while (q < len && w[q] != 0)
        q++;
    slen = q;
    lim = guard ? (slen < n ? slen : n) : slen;   /* <<< THE GUARD */
    for (i = 0; i < lim; i++)
        dst[dlen++] = w[i];
    for (i = 0; i < dlen; i++)
        acc = acc * 31 + (uint64_t)dst[i];
    return acc * 31 + (uint64_t)dlen;
}

int main(int argc, char **argv)
{
    size_t n, slen, i;
    int guard;

    if (argc != 4) {
        fprintf(stderr, "usage: %s <n> <slen> <guard 0|1>\n", argv[0]);
        return 2;
    }
    n = (size_t)strtoul(argv[1], NULL, 10);
    slen = (size_t)strtoul(argv[2], NULL, 10);
    guard = atoi(argv[3]);
    if (slen + 1 > sizeof src)
        return 2;
    for (i = 0; i < slen; i++)
        src[i] = (uint8_t)(1 + (i * 7 + 3) % 251);
    src[slen] = 0;

    printf("%llu\n", (unsigned long long)kern(src, slen + 1, n, guard));
    return 0;
}
"""

#: (n, slen, guard, what it is)
CASES = [
    (128, 140, 1, "threshold == sizeof dst, guard PRESENT  (p12's R1h)"),
    (128, 140, 0, "threshold == sizeof dst, guard DELETED   (p12's R1)"),
    (64, 100, 1, "threshold  < sizeof dst, guard PRESENT  (p13's strncpy)"),
    (64, 100, 0, "threshold  < sizeof dst, guard DELETED   (p13's strcpy)"),
]


def main():
    if not os.path.exists(CLANG):
        print(f"threshold_probe.py: no clang at {CLANG}", file=sys.stderr)
        return 1
    os.makedirs(OUT, exist_ok=True)
    csrc = os.path.join(OUT, "threshold_probe.c")
    binary = os.path.join(OUT, "threshold_probe")
    with open(csrc, "w") as f:
        f.write(SRC)
    cmd = [CLANG, "-std=c99", "-Wall", "-Wextra", "-O1", "-g",
           "-fsanitize=address,undefined", csrc, "-o", binary]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stdout + r.stderr, file=sys.stderr)
        return 1
    print(f"  {os.path.relpath(csrc, REPO)}\n")
    print(f"{'n':>4s} {'slen':>5s} {'guard':>6s} {'rc':>3s} {'sanitizer':>12s}  "
          f"{'checksum':>21s}  what")
    for n, slen, guard, what in CASES:
        p = subprocess.run([binary, str(n), str(slen), str(guard)],
                           capture_output=True, text=True, timeout=300)
        blob = p.stdout + p.stderr
        san = "OOB WRITE" if "AddressSanitizer" in blob else \
              ("UB" if "runtime error" in blob else "clean")
        digits = [l for l in p.stdout.splitlines() if l.strip().isdigit()]
        print(f"{n:4d} {slen:5d} {guard:6d} {p.returncode:3d} {san:>12s}  "
              f"{(digits[-1] if digits else '-'):>21s}  {what}")
    print("\nThe two guarded rows differ from their unguarded twins, so the "
          "guard FIRES in both.\nOnly the first pair puts the unguarded rung "
          "out of bounds. ../NOTES.md 1b.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
