#!/usr/bin/env python3
"""p47's proof mutants: the two that MUST FAIL, and the one that MUST PASS.

    python3 patterns/p47-ct-compare/controls/proof_mutants.py

The mutants themselves are generated by `gen_controls.py` (exact-string
substitution on `../verus.rs`, so "differs in exactly this" is a property of a
committed file rather than a claim about a hand-edit). This script runs them and
checks the verdicts, so a regression in `verus.rs`'s specification — one that
made an obligation vacuous — turns this script red.

    m_noguard   the window guard `len - p >= 2 * tlen` deleted.   MUST FAIL
    m_hdr       the second tag's read shifted by one byte.        MUST FAIL
    m_leak      the constant-time tag loop replaced by an
                EARLY-EXITING one that computes the same verdict. MUST PASS

⚠ **`m_leak` passing is p47's deliverable, not a defect.** It is `c/kernel.c`'s
bug promoted into the proved rung, and Verus accepts it against the same
`ensures` at the same obligation count plus one ghost lemma. The compiled
binary then leaks +7088 Ir/call between two inputs with identical checksums
(`../NOTES.md` 6). The reason no strengthening of the `ensures` can exclude it
is `lemma_xacc_sticky` itself: once the accumulator is non-zero it stays
non-zero, so the two programs are the same function of the input, and a
postcondition over the returned VALUE cannot separate them.

This script exits non-zero if any verdict is not the declared one.
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PDIR = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(PDIR))
CTL = os.path.join(REPO, ".temp", "p47", "ctl")
VERUS = os.path.join(REPO, "verus_run.py")

#: (name, must_verify, what the rejection is expected to say)
MUTANTS = [
    ("m_noguard", False, "invariant not satisfied before loop"),
    ("m_hdr", False, "precondition not satisfied"),
    ("m_leak", True, ""),
]


def run(path):
    r = subprocess.run([sys.executable, VERUS, path], capture_output=True,
                       text=True, cwd=REPO)
    txt = r.stdout + r.stderr
    m = re.search(r"(\d+) verified, (\d+) errors", txt)
    errs = [ln.strip() for ln in txt.splitlines() if ln.startswith("error:")]
    return (int(m.group(1)) if m else None, int(m.group(2)) if m else None,
            errs, r.returncode)


def main():
    if not os.path.isdir(CTL):
        raise SystemExit("proof_mutants.py: run gen_controls.py first "
                         f"(no {CTL})")
    print("# p47 proof mutants")
    bad = 0
    ver, err, _e, _rc = run(os.path.join(PDIR, "verus.rs"))
    print(f"  {'CONTROL verus.rs':16s} {ver} verified, {err} errors")
    if (ver, err) != (12, 0):
        print("    ⚠ the unmutated file does not verify 12/0 -- every verdict "
              "below is meaningless")
        bad += 1
    for name, must_pass, expect in MUTANTS:
        p = os.path.join(CTL, name + ".rs")
        if not os.path.exists(p):
            print(f"  {name:16s} MISSING {p}")
            bad += 1
            continue
        ver, err, errs, rc = run(p)
        passed = (rc == 0)
        ok = passed == must_pass
        tag = "MUST PASS" if must_pass else "MUST FAIL"
        print(f"  {name:16s} {tag}  ->  {ver} verified, {err} errors"
              f"   {'OK' if ok else '⚠ WRONG VERDICT'}")
        for e in errs[:3]:
            print(f"      {e}")
        if expect and not any(expect in e for e in errs):
            print(f"      ⚠ expected the rejection to mention {expect!r}")
        if not ok:
            bad += 1
    print(f"\n# {'all verdicts as declared' if not bad else str(bad) + ' WRONG'}")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
