#!/usr/bin/env python3
"""p49 CONTROLS: **the rung WITHOUT the safety line, in safe Rust and in unsafe
Rust -- and what Miri says about it, which is NOTHING.**

    python3 patterns/p49-interned-pool/controls/rust_bug.py

WHY THIS EXISTS
---------------
Most patterns in this tree ship an arm like this to show that Miri SEES the harm
the shipped rung avoids. **On p49 the point is the opposite, and it is the row's
headline**: delete the safety line from R2 or from R4 and you get a program that
computes `c/kernel.c`'s wrong answer with **no undefined behaviour anywhere** --
so Miri is silent, exactly as ASan and UBSan are. Nothing is allocated, nothing
is freed, no pointer dangles, and every index is in bounds.

⚠⚠ **A SILENT INSTRUMENT PROVES NOTHING WITHOUT A CONTROL THAT SPEAKS.** So
this file also builds an arm with genuine, Miri-visible undefined behaviour --
an out-of-range `get_unchecked` -- and requires Miri to report it. On a row where
every detector is silent, the must-fire arm is the whole of the evidence that the
silence is a fact about the program.

WHAT IT BUILDS, all by ASSERTED substitution on the SHIPPED rungs so that the
arms cannot drift away from the rungs they are variants of:

  * `arm_safe_bug.rs`   -- `../safe_naive.rs` with the copy-on-write block
                           deleted. ⚠ **SAFE Rust, no `unsafe` token anywhere**,
                           and it reproduces `c/kernel.c` exactly. That is
                           `CLAUDE.md` rule 6's *safe Rust reproduces the bug*
                           finding, on the SHIPPED representation rather than on
                           an `Rc` port (`controls/safe_arms.py` is the other
                           half).
  * `arm_unsafe_bug.rs` -- `../unsafe.rs` with the same block deleted.
  * `arm_miri_ctl.rs`   -- the must-fire arm: `get_unchecked` past the end.

WHAT IT ASSERTS
---------------
  * both bug arms print `c/kernel.c`'s answer on every shipped input;
  * `arm_safe_bug.rs` contains no `unsafe` token;
  * Miri reports NO undefined behaviour on either bug arm, on any input;
  * Miri DOES report undefined behaviour on `arm_miri_ctl.rs`.
"""

import glob
import hashlib
import json
import os
import re
import struct
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
PDIR = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(PDIR))
COMMON = os.path.join(REPO, "common")
CDIR = os.path.join(PDIR, "c")
SCRATCH = os.path.join(REPO, ".temp", "p49ctl", "rust_bug")
sys.path.insert(0, os.path.join(REPO, "harness"))
import build as buildmod  # noqa: E402

RUSTC = os.environ.get("SLB_RUSTC", os.path.expanduser("~/.cargo/bin/rustc"))
GCC = os.environ.get("SLB_GCC", "/usr/bin/gcc")
NIGHTLY = "nightly-x86_64-unknown-linux-gnu"
MIRI_BIN = os.path.expanduser(f"~/.rustup/toolchains/{NIGHTLY}/bin/miri")
CARGO = os.path.expanduser("~/.cargo/bin/cargo")
MIRI_ITERS = 4
MIRI_TIMEOUT = 300

SAFE_BLOCK = """                if rshd[t] == 1 {
                    if pbump + (rlen[t] as usize) > MEM {
                        SENT
                    } else {
                        let mut j: u8 = 0;
                        while j < rlen[t] {
                            mem[pbump + j as usize] = mem[roff[t] as usize + j as usize];
                            j = j + 1;
                        }
                        roff[t] = pbump as u8;
                        rshd[t] = 0;
                        mem[pbump] = 0;
                        pbump = pbump + rlen[t] as usize;
                        2
                    }
                } else {
                    mem[roff[t] as usize] = 0;
                    2
                }"""
SAFE_BUG = """                {
                    // THE SAFETY LINE IS DELETED HERE. Generated by
                    // controls/rust_bug.py from ../safe_naive.rs.
                    mem[roff[t] as usize] = 0;
                    2
                }"""

UNSAFE_BLOCK = """                if arr_get_unchecked(&rshd, t) == 1 {
                    let rl: u8 = arr_get_unchecked(&rlen, t);
                    if pbump + (rl as usize) > MEM {
                        SENT
                    } else {
                        let ro: u8 = arr_get_unchecked(&roff, t);
                        copy_bytes(&mut mem, pbump, ro as usize, rl);
                        arr_set_unchecked(&mut roff, t, pbump as u8);
                        arr_set_unchecked(&mut rshd, t, 0);
                        arr_set_unchecked(&mut mem, pbump, 0);
                        pbump = pbump + rl as usize;
                        2
                    }
                } else {
                    let ro: u8 = arr_get_unchecked(&roff, t);
                    arr_set_unchecked(&mut mem, ro as usize, 0);
                    2
                }"""
UNSAFE_BUG = """                {
                    // THE SAFETY LINE IS DELETED HERE. Generated by
                    // controls/rust_bug.py from ../unsafe.rs.
                    let ro: u8 = arr_get_unchecked(&roff, t);
                    arr_set_unchecked(&mut mem, ro as usize, 0);
                    2
                }"""

MIRI_CTL = """// p49 MUST-FIRE ARM for the Miri column. Generated by controls/rust_bug.py.
//
// p49's own rungs -- shipped and buggy alike -- execute no undefined behaviour,
// so Miri is silent on all of them. That silence is only evidence if Miri can be
// shown to be speaking, and this is the file that shows it: an unchecked read
// one element past the end of an array, which is exactly the class of mistake a
// trusted `get_unchecked` wrapper could hide.
fn main() {
    let v: [u8; 4] = [1, 2, 3, 4];
    // From the environment so the index is not a compile-time constant.
    let i: usize = std::env::args().count() + 3;
    let x: u8 = unsafe { *v.get_unchecked(i) };
    println!("{}", x);
}
"""


def env():
    e = dict(os.environ)
    e.pop("LD_PRELOAD", None)
    return e


def gen(src_name, block, repl, out_name):
    """One arm, by asserted substitution on a SHIPPED rung."""
    src = open(os.path.join(PDIR, src_name)).read()
    n = src.count(block)
    assert n == 1, (f"rust_bug.py: expected exactly 1 safety-line block in "
                    f"{src_name}, found {n} -- the rung has been respelled and "
                    f"this generator has to be updated with it")
    src = src.replace(block, repl)
    old_path = '#[path = "../../common/driver.rs"]'
    new_path = f'#[path = "{os.path.join(COMMON, "driver.rs")}"]'
    n2 = src.count(old_path)
    assert n2 == 1, f"rust_bug.py: expected 1 driver #[path], found {n2}"
    src = src.replace(old_path, new_path)
    src = "#![allow(dead_code, unused_imports)]\n" + src
    out = os.path.join(SCRATCH, out_name)
    open(out, "w").write(src)
    print(f"  {out_name:20s} <- {src_name}  (2 substitutions, both asserted)")
    return out


def build_rust(src, out):
    cmd = ([RUSTC] + buildmod.rust_flags("O3", "isolated", "unwind")
           + [src, "-o", out])
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=900)
    if r.returncode != 0:
        raise SystemExit(f"rust_bug.py: build failed for {src}:\n"
                         f"{r.stderr[-3000:]}")
    return out


def build_c(kernel, out):
    cmd = [GCC, "-std=c99", "-O3", "-DSLB_ISOLATED", "-I", COMMON, "-I", CDIR,
           os.path.join(COMMON, "driver.c"), os.path.join(CDIR, kernel),
           os.path.join(CDIR, "main.c"), "-o", out]
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
    if r.returncode != 0:
        raise SystemExit(f"rust_bug.py: C build failed:\n{r.stderr}")
    return out


def run(exe, path):
    r = subprocess.run([exe, path], capture_output=True, text=True,
                       timeout=900, env=env())
    return r.stdout.strip()


def probe_input(src, n_iters, out):
    blob = open(src, "rb").read()
    open(out, "wb").write(struct.pack("<Q", n_iters) + blob[8:])
    return out


def miri_sysroot():
    r = subprocess.run([CARGO, f"+{NIGHTLY}", "miri", "setup",
                        "--print-sysroot"], capture_output=True, text=True,
                       timeout=900)
    return r.stdout.strip() if r.returncode == 0 and r.stdout.strip() else None


def miri(src, sysroot, *args):
    e = env()
    e.pop("MIRIFLAGS", None)
    r = subprocess.run([MIRI_BIN, "--sysroot", sysroot, "--edition", "2021",
                        "-Zmiri-disable-isolation", src, "--", *args],
                       capture_output=True, text=True, timeout=MIRI_TIMEOUT,
                       cwd=PDIR, env=e)
    ub = ("Undefined Behavior" in r.stderr or "error: unsupported" in r.stderr)
    return {"rc": r.returncode, "ub": ub,
            "stdout": r.stdout.strip(),
            "first_error": next((l.strip() for l in r.stderr.splitlines()
                                 if "error" in l), "")}


def derived_from():
    out = {}
    for rel in ("patterns/p49-interned-pool/safe_naive.rs",
                "patterns/p49-interned-pool/unsafe.rs",
                "patterns/p49-interned-pool/c/kernel.c",
                "patterns/p49-interned-pool/inputs/gen.py",
                "patterns/p49-interned-pool/controls/rust_bug.py"):
        p = os.path.join(REPO, rel)
        out[rel] = hashlib.sha256(open(p, "rb").read()).hexdigest()
    return out


def main():
    os.makedirs(SCRATCH, exist_ok=True)
    problems = []
    inputs = sorted(glob.glob(os.path.join(PDIR, "inputs", "*.bin")))
    if not inputs:
        print("rust_bug.py: no .bin files -- run inputs/gen.py first",
              file=sys.stderr)
        return 1

    print("1. the arms, generated from the SHIPPED rungs")
    safe = gen("safe_naive.rs", SAFE_BLOCK, SAFE_BUG, "arm_safe_bug.rs")
    unsafe_ = gen("unsafe.rs", UNSAFE_BLOCK, UNSAFE_BUG, "arm_unsafe_bug.rs")
    ctl = os.path.join(SCRATCH, "arm_miri_ctl.rs")
    open(ctl, "w").write(MIRI_CTL)

    body = open(safe).read()
    body = re.sub(r"//.*", "", body)
    n_unsafe = len(re.findall(r"\bunsafe\b", body))
    print(f"  `unsafe` tokens in arm_safe_bug.rs (comments blanked): {n_unsafe}")
    if n_unsafe:
        problems.append(
            f"arm_safe_bug.rs contains {n_unsafe} `unsafe` token(s); the whole "
            f"claim is that this rung is SAFE Rust and still has the bug")

    exes = {"safe_bug": build_rust(safe, os.path.join(SCRATCH, "safe_bug")),
            "unsafe_bug": build_rust(unsafe_, os.path.join(SCRATCH,
                                                          "unsafe_bug"))}
    ref = {"R1": build_c("kernel.c", os.path.join(SCRATCH, "R1"))}

    print(f"\n2. both bug arms against c/kernel.c\n{'input':32s} "
          f"{'c/kernel.c':>21s} {'safe_bug':>10s} {'unsafe_bug':>12s}")
    rows = []
    for path in inputs:
        name = os.path.basename(path)
        want = run(ref["R1"], path)
        got = {k: run(v, path) for k, v in exes.items()}
        rows.append({"input": name, "c_kernel_c": want, **got})
        print(f"{name:32s} {want:>21s} "
              f"{'==' if got['safe_bug'] == want else got['safe_bug']:>10s} "
              f"{'==' if got['unsafe_bug'] == want else got['unsafe_bug']:>12s}")
        for k, v in got.items():
            if v != want:
                problems.append(f"{name}: {k} printed {v}, c/kernel.c printed "
                                f"{want} -- the arm is claimed to reproduce the "
                                f"buggy C rung exactly")

    # ---- 3. Miri ----------------------------------------------------------
    print("\n3. MIRI -- silent on the bug arms, and the must-fire arm that "
          "shows it is speaking")
    miri_rows = []
    sysroot = miri_sysroot() if os.path.exists(MIRI_BIN) else None
    if sysroot is None:
        problems.append(
            f"miri not found at {MIRI_BIN} (or `cargo miri setup` failed), so "
            f"the Miri column below did not run at all. On p49 that column is "
            f"part of the headline and its absence is a BLOCKED row, not a pass")
        print("    miri unavailable -- column blocked")
    else:
        c = miri(ctl, sysroot)
        miri_rows.append({"arm": "arm_miri_ctl.rs", "input": None, **c})
        print(f"    {'arm_miri_ctl.rs':22s} {'MUST FIRE':12s} "
              f"ub={c['ub']}  {c['first_error'][:90]}")
        if not c["ub"]:
            problems.append(
                "THE MIRI MUST-FIRE ARM DID NOT FIRE. Every Miri row below is "
                "then indistinguishable from a Miri that is not running, and "
                "p49's `Miri is silent' result has no evidence behind it")
        for arm, src in (("arm_safe_bug.rs", safe),
                         ("arm_unsafe_bug.rs", unsafe_)):
            for path in inputs:
                name = os.path.basename(path)
                probe = probe_input(path, MIRI_ITERS,
                                    os.path.join(SCRATCH, "miri." + name))
                r = miri(src, sysroot, probe)
                miri_rows.append({"arm": arm, "input": name, **r})
                print(f"    {arm:22s} {name:28s} ub={r['ub']}"
                      + ("" if not r["ub"] else
                         f"  <-- {r['first_error'][:80]}"))
                if r["ub"]:
                    problems.append(
                        f"Miri reports undefined behaviour in {arm} on {name}. "
                        f"p49's claim is that the BUGGY rung executes none -- "
                        f"that is the row's headline, and a hit refutes it")

    doc = {"pin": {"regenerate": "python3 patterns/p49-interned-pool/controls/"
                                 "rust_bug.py"},
           "derived_from_sha256": derived_from(),
           "measured_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
           "unsafe_tokens_in_safe_bug_arm": n_unsafe,
           "answers": rows,
           "miri": miri_rows,
           "miri_probe_iters": MIRI_ITERS,
           "problems": problems,
           "invariant": "Deleting the safety line from R2 (SAFE Rust, zero "
                        "`unsafe` tokens) or from R4 reproduces c/kernel.c's "
                        "answer exactly on every shipped input, and Miri reports "
                        "NO undefined behaviour on either arm on any of them -- "
                        "while reporting it immediately on a must-fire arm built "
                        "and run the same way. p49's harm is invisible to Miri "
                        "for the same reason it is invisible to ASan and UBSan: "
                        "there is no undefined behaviour to see."}
    out = os.path.join(HERE, "rust_bug.json")
    json.dump(doc, open(out, "w"), indent=2)
    print(f"wrote {out}")
    for p in problems:
        print(f"  *** {p}", file=sys.stderr)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
