#!/usr/bin/env python3
"""p49 CONTROLS: **the two repair spellings, built and priced side by side.**

    python3 patterns/p49-interned-pool/controls/spellings.py

WHY THIS EXISTS
---------------
`CVE-2022-40304` has two working repairs and they sit at different sites:

  * **`cow` -- copy-on-write at the MUTATION site.** `c/kernel_hardened.c`, and
    what this pattern ships as R1h: before the cycle-breaker writes, ask whether
    the buffer is the record's to write and un-share if it is not.
  * **`provenance` -- never borrow, at the DEFINE site.** Upstream commit
    `644a89e`: content is always copied into the record's own storage, so no two
    records ever share a buffer and the write-through cannot happen.

⚠⚠ **`TASK_160` MEASURED THAT UPSTREAM'S SPELLING CHANGES A BENIGN OBSERVABLE**
on the port -- `10 passed, 0 failed` becomes `9 passed, 1 failed`, and
`"interned":true` becomes `false` in `GET /doc/0/entities` -- while copy-on-write
is byte-identical to the bug on benign input. **That is why `cow` is the safety
line and upstream's patch is a control.** ⚠ *An upstream patch is not
automatically a safety line; check it against the benign observable.*

This file reproduces that result INSIDE the row rather than inheriting it. The
kernel's epilogue folds each record's ownership flag beside its content -- the
reduction of the port's `"interned"` field -- so the benign observable is in the
checksum, and the question is decidable.

HOW THE PROVENANCE ARM IS BUILT
-------------------------------
By ONE asserted substitution on `c/kernel.c`: the threshold test
`w < P49_THRESH` becomes `0`, so every DEFINE takes the private path and no
record is ever created shared. That is exactly upstream's change of provenance,
and it is generated rather than hand-written so that it cannot drift away from
the rung it is a variant of. ⚠ The substitution count is asserted
(`CLAUDE.md` constraint 1).

WHAT IT MEASURES
----------------
  1. **the benign observable** -- every arm's checksum on every shipped input;
  2. **the price** -- static instruction count of the kernel symbol, and
     marginal `Ir` per kernel call from a difference of two callgrind runs at
     100 and 200 iterations, for all three arms at BOTH optimisation levels on
     BOTH compilers. ⚠ Both levels and both compilers, because
     `.memory/03-measurement.md` and `p35` between them have shown the
     comparison can reverse.

WHAT IT ASSERTS
---------------
  * `cow` is byte-identical to `bug` on every NON-adversarial input;
  * `provenance` DIFFERS from `bug` on at least one non-adversarial input --
    i.e. it changes a benign observable, which is the finding;
  * both repairs differ from `bug` on every adversarial input except
    `adversarial-stride3.bin`, i.e. both really do repair;
  * every marginal `Ir` figure is reported per (arm, compiler, level) CELL and
    never maxed across one (`.memory/03-measurement.md` entry 23's rule).
"""

import glob
import hashlib
import json
import os
import re
import struct
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
PDIR = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(PDIR))
COMMON = os.path.join(REPO, "common")
CDIR = os.path.join(PDIR, "c")
SCRATCH = os.path.join(REPO, ".temp", "p49ctl", "spellings")
sys.path.insert(0, os.path.join(REPO, "harness"))
import asm  # noqa: E402

GCC = os.environ.get("SLB_GCC", "/usr/bin/gcc")
CLANG = os.environ.get("SLB_CLANG", os.path.expanduser("~/tools/llvm/bin/clang"))
VALGRIND = os.path.expanduser("~/tools/valgrind/bin/valgrind")

PROBE_ITERS = (100, 200)
NO_DIVERGE = ("adversarial-stride3.bin",)


def make_provenance():
    """`c/kernel.c` with the INLINE THRESHOLD forced false -- upstream's change
    of provenance, generated by one asserted substitution."""
    src = open(os.path.join(CDIR, "kernel.c")).read()
    old = "            } else if (w < P49_THRESH) {"
    new = ("            } else if (0) { /* PROVENANCE ARM (upstream 644a89e):\n"
           "                * content is NEVER interned, so no two records ever\n"
           "                * share a buffer and the write-through cannot\n"
           "                * happen. Generated by controls/spellings.py. */")
    n = src.count(old)
    assert n == 1, f"spellings.py: expected 1 threshold site, found {n}"
    src = src.replace(old, new)
    os.makedirs(SCRATCH, exist_ok=True)
    out = os.path.join(SCRATCH, "kernel_provenance.c")
    open(out, "w").write(src)
    print(f"  provenance arm generated: 1 substitution (asserted)")
    return out


def build(cc, opt, kernel_path, out):
    cmd = [cc, "-std=c99", "-Wall", "-Wextra", "-g",
           "-O0" if opt == "O0" else "-O3", "-DSLB_ISOLATED",
           "-I", COMMON, "-I", CDIR,
           os.path.join(COMMON, "driver.c"), kernel_path,
           os.path.join(CDIR, "main.c"), "-o", out]
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
    if r.returncode != 0:
        raise SystemExit(f"spellings.py: build failed:\n{' '.join(cmd)}\n"
                         f"{r.stderr}")
    return out


def env():
    e = dict(os.environ)
    e.pop("LD_PRELOAD", None)
    return e


def run(exe, path):
    r = subprocess.run([exe, path], capture_output=True, text=True,
                       timeout=900, env=env())
    return r.stdout.strip()


def probe_input(src, n_iters, out):
    """The same input with `n_iters` rewritten -- offset 0 of every pattern's
    input file (`.memory/02-bench-rules.md`), so this is a format-level
    operation."""
    blob = open(src, "rb").read()
    open(out, "wb").write(struct.pack("<Q", n_iters) + blob[8:])
    return out


_IR = re.compile(r"I\s+refs:\s+([0-9,]+)")


def callgrind_ir(exe, path):
    out = os.path.join(SCRATCH, "cg.out")
    r = subprocess.run([VALGRIND, "--tool=callgrind", "--callgrind-out-file=" + out,
                        exe, path], capture_output=True, text=True, timeout=1800,
                       env=env())
    m = _IR.search(r.stderr)
    if not m:
        raise SystemExit(f"spellings.py: no `I refs` from callgrind:\n{r.stderr[-800:]}")
    if os.path.exists(out):
        os.unlink(out)
    return int(m.group(1).replace(",", ""))


def derived_from():
    out = {}
    for rel in ("patterns/p49-interned-pool/c/kernel.c",
                "patterns/p49-interned-pool/c/kernel_hardened.c",
                "patterns/p49-interned-pool/c/main.c",
                "patterns/p49-interned-pool/inputs/gen.py",
                "patterns/p49-interned-pool/controls/spellings.py"):
        p = os.path.join(REPO, rel)
        out[rel] = hashlib.sha256(open(p, "rb").read()).hexdigest()
    return out


def main():
    os.makedirs(SCRATCH, exist_ok=True)
    problems = []
    prov = make_provenance()
    arms = {"bug": os.path.join(CDIR, "kernel.c"),
            "cow": os.path.join(CDIR, "kernel_hardened.c"),
            "provenance": prov}
    ccs = [("gcc", GCC)]
    if os.path.exists(CLANG):
        ccs.append(("clang", CLANG))
    else:
        problems.append(f"clang not found at {CLANG}; the clang column is "
                        f"missing and no C-vs-C claim here may be generalised")
    inputs = sorted(glob.glob(os.path.join(PDIR, "inputs", "*.bin")))
    if not inputs:
        print("spellings.py: no .bin files -- run inputs/gen.py first",
              file=sys.stderr)
        return 1

    # ---- 1. the benign observable -----------------------------------------
    exes = {}
    for arm, src in arms.items():
        for tag, cc in ccs:
            for opt in ("O0", "O3"):
                exes[(arm, tag, opt)] = build(
                    cc, opt, src, os.path.join(SCRATCH, f"{arm}.{tag}.{opt}"))

    print("\n1. THE BENIGN OBSERVABLE -- every arm's checksum on every input")
    print(f"{'input':32s} {'bug':>22s} {'cow':>22s} {'provenance':>22s}")
    ans = {}
    for path in inputs:
        name = os.path.basename(path)
        row = {}
        for arm in arms:
            vals = {run(exes[(arm, tag, opt)], path)
                    for tag, _ in ccs for opt in ("O0", "O3")}
            if len(vals) != 1:
                problems.append(f"{name}: arm `{arm}` gives {len(vals)} "
                                f"different answers across compiler x level "
                                f"({vals}) -- an answer that depends on the "
                                f"optimiser is not an answer")
            row[arm] = sorted(vals)[0]
        ans[name] = row
        adv = name.startswith("adversarial-")
        print(f"{name:32s} {row['bug']:>22s} {row['cow']:>22s} "
              f"{row['provenance']:>22s}" + ("   <-- adversarial" if adv else ""))
        if not adv:
            if row["cow"] != row["bug"]:
                problems.append(
                    f"{name} is a MATRIX input and `cow` differs from `bug`, so "
                    f"the shipped safety line is NOT benign-invisible")
        if adv and name not in NO_DIVERGE:
            for arm in ("cow", "provenance"):
                if row[arm] == row["bug"]:
                    problems.append(
                        f"{name} is ADVERSARIAL and `{arm}` gives the same "
                        f"answer as `bug`, so it does not repair it")

    benign = [n for n in ans if not n.startswith("adversarial-")]
    prov_moves = [n for n in benign if ans[n]["provenance"] != ans[n]["bug"]]
    cow_moves = [n for n in benign if ans[n]["cow"] != ans[n]["bug"]]
    print(f"\n  benign inputs on which `cow` moves the answer       : "
          f"{len(cow_moves)} of {len(benign)}  {cow_moves}")
    print(f"  benign inputs on which `provenance` moves the answer: "
          f"{len(prov_moves)} of {len(benign)}  {prov_moves}")
    if not prov_moves:
        problems.append(
            "`provenance` changes NO benign observable here, so this row does "
            "not reproduce TASK_160's measurement on the port and the choice of "
            "`cow` as the safety line is unsupported by this control")

    # ---- 2. the price -----------------------------------------------------
    print("\n2. THE PRICE -- static instructions and marginal Ir per kernel "
          "call, per CELL")
    small = os.path.join(PDIR, "inputs", "small.bin")
    p_lo = probe_input(small, PROBE_ITERS[0], os.path.join(SCRATCH, "lo.bin"))
    p_hi = probe_input(small, PROBE_ITERS[1], os.path.join(SCRATCH, "hi.bin"))
    price = []
    have_vg = os.path.exists(VALGRIND)
    if not have_vg:
        problems.append(f"valgrind not found at {VALGRIND}; no marginal Ir was "
                        f"measured and the price column below is static only")
    print(f"{'arm':12s} {'cc':6s} {'opt':4s} {'n_fn_nopad':>10s} "
          f"{'marginal Ir/call':>17s}")
    for arm in arms:
        for tag, _ in ccs:
            for opt in ("O0", "O3"):
                exe = exes[(arm, tag, opt)]
                k = asm.try_kernel(exe, "kernel")
                nfn = k.n_fn_nopad if k else None
                mir = None
                if have_vg:
                    lo = callgrind_ir(exe, p_lo)
                    hi = callgrind_ir(exe, p_hi)
                    mir = (hi - lo) / float(PROBE_ITERS[1] - PROBE_ITERS[0])
                price.append({"arm": arm, "cc": tag, "opt": opt,
                              "n_fn_nopad": nfn, "marginal_ir_per_call": mir})
                print(f"{arm:12s} {tag:6s} {opt:4s} {nfn if nfn else 0:10d} "
                      + (f"{mir:17.2f}" if mir is not None else f"{'--':>17s}"))

    print("\n  the two repairs, priced against the bug, PER CELL "
          "(never maxed across one):")
    by = {(r["arm"], r["cc"], r["opt"]): r for r in price}
    deltas = []
    for tag, _ in ccs:
        for opt in ("O0", "O3"):
            b = by[("bug", tag, opt)]
            for arm in ("cow", "provenance"):
                r = by[(arm, tag, opt)]
                d_ins = (r["n_fn_nopad"] - b["n_fn_nopad"]
                         if r["n_fn_nopad"] and b["n_fn_nopad"] else None)
                d_ir = (r["marginal_ir_per_call"] - b["marginal_ir_per_call"]
                        if r["marginal_ir_per_call"] is not None
                        and b["marginal_ir_per_call"] is not None else None)
                deltas.append({"arm": arm, "cc": tag, "opt": opt,
                               "d_instructions": d_ins, "d_marginal_ir": d_ir})
                print(f"    {arm:12s} {tag:6s} {opt:4s}  "
                      f"instructions {d_ins:+d}   "
                      + (f"marginal Ir/call {d_ir:+.2f}" if d_ir is not None
                         else "marginal Ir/call --"))

    doc = {"pin": {"regenerate": "python3 patterns/p49-interned-pool/controls/"
                                 "spellings.py"},
           "derived_from_sha256": derived_from(),
           "measured_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
           "compilers": [t for t, _ in ccs],
           "answers": ans,
           "benign_inputs": benign,
           "cow_moves_benign": cow_moves,
           "provenance_moves_benign": prov_moves,
           "price": price,
           "deltas_vs_bug": deltas,
           "probe_iters": list(PROBE_ITERS),
           "probe_input": "small.bin",
           "problems": problems,
           "invariant": "`cow` -- the shipped safety line -- changes NO benign "
                        "observable; `provenance`, which is upstream's patch, "
                        "changes at least one. Both repair every adversarial "
                        "input except adversarial-stride3.bin. The price of each "
                        "is reported per (arm, compiler, level) CELL and never "
                        "maxed across one."}
    out = os.path.join(HERE, "spellings.json")
    json.dump(doc, open(out, "w"), indent=2)
    print(f"wrote {out}")
    for p in problems:
        print(f"  *** {p}", file=sys.stderr)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
