#!/usr/bin/env python3
"""Generate p14's control cells into `.temp/p14/ctl/`, by EXACT-STRING
substitution on the shipped sources, asserting the hit count of every edit.

`.memory/05-layout.md` item 11: a control that lives only in gitignored scratch
is the self-certifying trap one level down, and a control derived by a
hand-edited copy drifts the moment a rung moves. So every control here is a
function of the committed rung sources plus the substitutions written below, and
the script fails loudly if a substitution stops matching.

    python3 patterns/p14-field-split/controls/gen_controls.py
    bash    patterns/p14-field-split/controls/build_controls.sh
    bash    patterns/p14-field-split/controls/verify_controls.sh

WHAT EACH CONTROL IS FOR
------------------------

**The priced fiats** -- ../spec.md's `forbidden` list. An entry the PROVER
already excludes costs nothing to keep; an entry only the DECLARATION excludes is
a fiat and must be priced beside the number it protects (TASK_049). p14's C
entries are all fiats, because C has no prover:

    c_strtok   R1h's scan replaced by libc `strtok`, which COLLAPSES runs of
               delimiters. It computes a DIFFERENT PARTITION, so it is not a
               rung -- but its cost is the price of the exclusion and
               ../NOTES.md 8 publishes it.
    c_memchr   R1h's scan replaced by libc `memchr`, which computes the SAME
               partition through an AVX2 IFUNC. This is the one that would move
               a number, and it is p11's result arriving on a fifth kernel.
    c_hcond    R1h's `if (nt == MAXTOK) break;` hoisted into the loop condition,
               `while (i <= m && nt < MAXTOK)`. Same table, same checksum: the
               CHEAPEST-FOUND in-contract hardening spelling, against the
               textbook one that ships.

**The second in-contract R3 spelling** -- `.memory/01-ladder.md` finding 3, which
four patterns have now got wrong by publishing a point instead of its class:

    t_1step    R3's window reslice in the ONE-STEP form `&buf[off..off + len]`
               instead of the two-step `split_at`. IN CONTRACT -- the reslice is
               one of exactly two things ../spec.md's declaration leaves free on
               R3 -- and it is `.memory/01-ladder.md` finding 3's canonical
               alternate, the p04 lever.
    t_idxfold  R3's iterator fold replaced by R2's indexed `while`, keeping the
               two-step reslice. IN CONTRACT: the declaration pins the fold's
               OPERATIONS and not its loop form. **These two are the second and
               third in-contract R3 spellings, and the cheapest of the three is
               what ../NOTES.md 8 quotes beside the shipped one.**
    t_pos      R3's indexed scan replaced by `rest.iter().position(...)` with the
               field-count bound hoisted into the loop head. **OUT of contract**
               -- it spells neither `if nt == MAXTOK {` nor `while i <= m {` nor
               `if i == m ||`, all three of which are `required` entries -- and it
               is measured anyway, because the price of a declaration is what the
               declaration EXCLUDES.
    t_split    R3's scan and table fill replaced by `scr[..m].split(|&b| b ==
               DELIM)`. OUT of contract (`forbidden[0]`), and the prover
               excludes it independently -- `verify_controls.sh` puts the
               matching R5 twin through `./verus_run.py` and reads the error
               text, which is this project's own test for support.

**The delete-the-check controls** -- ../NOTES.md 7, the row the pattern exists
for. Each is a rung with the field-count bound removed and NOTHING else:

    n_nocap    safe_naive without it -- PANICS where C corrupts its frame
    t_nocap    safe_tuned without it
    u_nocap    unsafe without it -- the one that reproduces C's UB in Rust

**The fold mutants** -- ../NOTES.md 2, which shows that each of the three folded
quantities catches a different wrong partition. These are CORRECTNESS controls
and are never measured for perf:

    m_nolen    the field LENGTH is not folded
    m_nocount  the field COUNT is not folded
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PDIR = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(PDIR))
OUT = os.path.join(REPO, ".temp", "p14", "ctl")

BANNER = ("/* GENERATED by patterns/p14-field-split/controls/gen_controls.py "
          "from the shipped rung source. DO NOT EDIT. */\n")
RBANNER = ("// GENERATED by patterns/p14-field-split/controls/gen_controls.py "
           "from the shipped rung source. DO NOT EDIT.\n")


def read(rel):
    return open(os.path.join(PDIR, rel)).read()


def sub(text, old, new, n=1, tag=""):
    got = text.count(old)
    if got != n:
        raise SystemExit(
            f"gen_controls.py: {tag}: expected {n} occurrence(s) of\n"
            f"---\n{old}\n---\ngot {got}. The shipped source moved; fix the "
            f"substitution rather than the control.")
    return text.replace(old, new)


def write(name, text, banner):
    os.makedirs(OUT, exist_ok=True)
    p = os.path.join(OUT, name)
    open(p, "w").write(banner + text)
    print(f"  {name:22s} {len(text):7d} B")
    return p


# ------------------------------------------------------------------ C ------
SCAN_C = """        nt = 0;
        s = 0;
        i = 0;
        while (i <= m) {
            if (i == m || scr[i] == DELIM) {
                /* >>> THE SAFETY LINE. c/kernel.c omits exactly this and
                 * nothing else. The table is fixed and the field count is a
                 * count of delimiters in attacker data. <<< */
                if (nt == MAXTOK)
                    break;
                flen = i - s;
                tl[nt] = flen;
                nt++;
                s = i + 1;
            }
            i++;
        }
"""

SCAN_C_HCOND = """        nt = 0;
        s = 0;
        i = 0;
        while (i <= m && nt < MAXTOK) {
            if (i == m || scr[i] == DELIM) {
                flen = i - s;
                tl[nt] = flen;
                nt++;
                s = i + 1;
            }
            i++;
        }
"""

SCAN_C_MEMCHR = """        nt = 0;
        s = 0;
        i = 0;
        while (i <= m && nt < MAXTOK) {
            const uint8_t *hit = (const uint8_t *)memchr(scr + s, DELIM, m - s);
            i = hit ? (size_t)(hit - scr) : m;
            flen = i - s;
            tl[nt] = flen;
            nt++;
            s = i + 1;
            i++;
        }
"""

SCAN_C_STRTOK = """        nt = 0;
        s = 0;
        i = 0;
        {
            char *tok;
            static const char dl[2] = { DELIM, 0 };
            scr[m] = 0;
            for (tok = strtok((char *)scr, dl); tok != NULL;
                 tok = strtok(NULL, dl)) {
                if (nt == MAXTOK)
                    break;
                flen = strlen(tok);
                tl[nt] = flen;
                nt++;
            }
        }
"""


def c_controls():
    h = read("c/kernel_hardened.c")
    write("c_hcond_kernel.c", sub(h, SCAN_C, SCAN_C_HCOND, 1, "c_hcond"), BANNER)
    write("c_memchr_kernel.c", sub(h, SCAN_C, SCAN_C_MEMCHR, 1, "c_memchr"),
          BANNER)
    # strtok needs one extra scratch byte for the NUL it writes, so the control
    # also widens the array -- and that widening is itself part of the price.
    t = sub(h, SCAN_C, SCAN_C_STRTOK, 1, "c_strtok")
    t = sub(t, "    uint8_t scr[SCR];", "    uint8_t scr[SCR + 1];", 1,
            "c_strtok scr")
    write("c_strtok_kernel.c", t, BANNER)


# --------------------------------------------------------------- Rust ------
SCAN_RS = """        while i <= m {
            if i == m || scr[i] == DELIM {
                // THE SAFETY LINE. c/kernel.c omits exactly this.
                if nt == MAXTOK {
                    break;
                }
                let flen: usize = i - s;
                tl[nt] = flen;
                nt = nt + 1;
                s = i + 1;
            }
            i = i + 1;
        }
"""

SCAN_RS_NOCAP = """        while i <= m {
            if i == m || scr[i] == DELIM {
                let flen: usize = i - s;
                tl[nt] = flen;
                nt = nt + 1;
                s = i + 1;
            }
            i = i + 1;
        }
"""

RESLICE_2STEP = "    let w: &[u8] = buf.split_at(off).1.split_at(len).0;\n"
RESLICE_1STEP = "    let w: &[u8] = &buf[off..off + len];\n"

FOLD_RS_ITER = """        let mut cur: usize = 0;
        for &tj in tl[..nt].iter() {
            acc = acc.wrapping_mul(31).wrapping_add(tj as u64);
            acc = scr[cur..cur + tj]
                .iter()
                .fold(acc, |h, &e| h.wrapping_mul(31).wrapping_add(e as u64));
            cur = cur + tj + 1;
        }
"""

FOLD_RS_IDX = """        let mut cur: usize = 0;
        let mut j: usize = 0;
        while j < nt {
            let tj: usize = tl[j];
            acc = acc.wrapping_mul(31).wrapping_add(tj as u64);
            let mut q: usize = 0;
            while q < tj {
                acc = acc.wrapping_mul(31).wrapping_add(scr[cur + q] as u64);
                q = q + 1;
            }
            cur = cur + tj + 1;
            j = j + 1;
        }
"""

SCAN_RS_POS = """        while i <= m && nt < MAXTOK {
            let hit = scr[s..m].iter().position(|&b| b == DELIM);
            i = match hit {
                Some(k) => s + k,
                None => m,
            };
            let flen: usize = i - s;
            tl[nt] = flen;
            nt = nt + 1;
            s = i + 1;
            i = i + 1;
        }
"""

SCAN_RS_SPLIT = """        for f in scr[..m].split(|&b| b == DELIM) {
            if nt == MAXTOK {
                break;
            }
            let flen: usize = f.len();
            tl[nt] = flen;
            nt = nt + 1;
        }
        let _ = (i, s);
"""

SCAN_U = """        while i <= m {
            if i == m || unsafe { *scr.get_unchecked(i) } == DELIM {
                // THE SAFETY LINE. c/kernel.c omits exactly this.
                if nt == MAXTOK {
                    break;
                }
                let flen: usize = i - s;
                unsafe { *tl.get_unchecked_mut(nt) = flen; }
                nt = nt + 1;
                s = i + 1;
            }
            i = i + 1;
        }
"""

SCAN_U_NOCAP = """        while i <= m {
            if i == m || unsafe { *scr.get_unchecked(i) } == DELIM {
                let flen: usize = i - s;
                unsafe { *tl.get_unchecked_mut(nt) = flen; }
                nt = nt + 1;
                s = i + 1;
            }
            i = i + 1;
        }
"""


def rust_controls():
    n = read("safe_naive.rs")
    t = read("safe_tuned.rs")
    u = read("unsafe.rs")
    write("n_nocap.rs", sub(n, SCAN_RS, SCAN_RS_NOCAP, 1, "n_nocap"), RBANNER)
    write("t_nocap.rs", sub(t, SCAN_RS, SCAN_RS_NOCAP, 1, "t_nocap"), RBANNER)
    write("u_nocap.rs", sub(u, SCAN_U, SCAN_U_NOCAP, 1, "u_nocap"), RBANNER)
    write("t_1step.rs", sub(t, RESLICE_2STEP, RESLICE_1STEP, 1, "t_1step"),
          RBANNER)
    write("t_idxfold.rs", sub(t, FOLD_RS_ITER, FOLD_RS_IDX, 1, "t_idxfold"),
          RBANNER)
    write("t_pos.rs", sub(t, SCAN_RS, SCAN_RS_POS, 1, "t_pos"), RBANNER)
    write("t_split.rs", sub(t, SCAN_RS, SCAN_RS_SPLIT, 1, "t_split"), RBANNER)
    # fold mutants: correctness controls, never measured for perf
    m1 = sub(n, "            acc = acc.wrapping_mul(31).wrapping_add(tj as u64);\n",
             "", 1, "m_nolen")
    write("m_nolen.rs", m1, RBANNER)
    m2 = sub(n, "        acc = acc.wrapping_mul(31).wrapping_add(nt as u64);\n",
             "", 1, "m_nocount")
    write("m_nocount.rs", m2, RBANNER)


# ------------------------------------------------- the R5 `.split(` twin ----
# Not a control cell: a PROBE, whose only job is to make the prover say whether
# `<[T]>::split` is available at the pinned vstd. `verify_controls.sh` runs it
# and reads the ERROR TEXT, not the exit code (`.memory/01-ladder.md`:
# `is not supported` disqualifies, `postcondition not satisfied` does not).
VERUS_SCAN = """        while i <= m
"""


def verus_probe():
    v = read("verus.rs")
    old = """            if i == m || scr_get_unchecked(&scr, i) == DELIM {"""
    new = """            if i == m || scr@.subrange(0, m as int).split_probe() == DELIM {"""
    del new  # the real probe is simpler: call <[T]>::split in exec position
    body = """                let _probe: usize = scr[..m].split(|b: &u8| *b == DELIM).count();
"""
    v2 = sub(v, old + "\n", body + old + "\n", 1, "verus split probe")
    write("v_split_probe.rs", v2, RBANNER)


# ------------------------------------------------------- the PROOF MUTANTS --
# `.memory/04-verus.md`: "Verification succeeding is not evidence that the
# specification says anything. Run mutants and check that each one FAILS."
# `.memory/05-layout.md` item 11: a deliberately-broken proof cannot live in the
# pattern dir (check.py requires every `verus!` file there to be pinned and to
# report 0 errors), so it ships as a `.temp/` artefact with THIS generator and a
# NOTES.md section carrying the diff, the commands and the measured output.
#
#   pm1_nocap    THE SAFETY LINE deleted from R5, and nothing else. The proof
#                must fail, at `tl_set_unchecked`'s `requires`, because that is
#                exactly R1's bug written in Rust.
#   pm2_weakreq  `tl_set_unchecked`'s `requires` weakened from `<` to `<=`. The
#                SHIPPED configuration may still verify -- the caller can prove
#                the stronger fact -- so this is a test of the TWIN, which must
#                fail because `v[i] = x` at `i == len` is out of bounds.
#   pm3_msonly   the safety line deleted AND the kernel's functional `ensures`
#                weakened to `true`. **This is the p06 comparison**: on p06 a
#                memory-safety-only spec ACCEPTED the buggy kernel in regime 1,
#                because nothing left the array. p14's bug is a spatial store,
#                so the prediction is that memory safety alone SUFFICES here --
#                and the mutant must still fail. Measured either way in
#                ../NOTES.md 10.

VERUS_SAFETY_LINE = """                // THE SAFETY LINE. c/kernel.c omits exactly this.
                if nt == MAXTOK {
                    break;
                }
"""


def verus_mutants():
    v = read("verus.rs")
    write("pm1_nocap.rs", sub(v, VERUS_SAFETY_LINE, "", 1, "pm1_nocap"), RBANNER)
    w = sub(v, """fn tl_set_unchecked(v: &mut [usize; 16], i: usize, x: usize)
    requires
        i < old(v)@.len(),""",
            """fn tl_set_unchecked(v: &mut [usize; 16], i: usize, x: usize)
    requires
        i <= old(v)@.len(),""", 1, "pm2_weakreq shipped")
    w = sub(w, """fn slb_twin_tl_set_unchecked(v: &mut [usize; 16], i: usize, x: usize)
    requires
        i < old(v)@.len(),""",
            """fn slb_twin_tl_set_unchecked(v: &mut [usize; 16], i: usize, x: usize)
    requires
        i <= old(v)@.len(),""", 1, "pm2_weakreq twin")
    write("pm2_weakreq.rs", w, RBANNER)
    m = sub(v, VERUS_SAFETY_LINE, "", 1, "pm3_msonly line")
    m = sub(m, """    ensures
        r == split_fold(buf@, off as int, len as int),
{""",
            """    ensures
        true,
{""", 1, "pm3_msonly ensures")
    # the driver's consuming assert names the deleted postcondition; drop it too,
    # or the mutant fails for a reason that is not the one under test.
    m = sub(m, """            assert(r == split_fold(buf@, (k * stride) as int, stride as int));
""", "", 1, "pm3_msonly assert")
    write("pm3_msonly.rs", m, RBANNER)


def main():
    print("p14 controls ->", os.path.relpath(OUT, os.getcwd()))
    c_controls()
    rust_controls()
    verus_probe()
    verus_mutants()
    return 0


if __name__ == "__main__":
    sys.exit(main())
