#!/usr/bin/env python3
"""ph45 control -- the 251-entity table is DERIVED from the pinned tarball, and
this is both the generator and the check.

`c/mbfl__html_entities.h` and the `ENT` table in all four `.rs` rungs are
`ext/mbstring/libmbfl/filters/html_entities.c:37-290` -- 251 entries plus the
`{NULL, -1}` terminator -- re-emitted in C and Rust syntax. They are GENERATED,
never typed, so a transcription error is not a thing this row can have.

    python3 controls/entity_table.py --check     # every shipped table == tarball
    python3 controls/entity_table.py --emit c    # regenerate the C header
    python3 controls/entity_table.py --emit rust # the Rust literal

⚠ The check has a MUST-FIRE negative built in (`--selftest`): it mutates one
entry of the parsed table and asserts the comparison rejects it, so a checker
that stopped comparing could not pass.
"""
import argparse
import os
import re
import subprocess
import sys

ROW = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = os.path.dirname(os.path.dirname(ROW))

TARBALL = os.environ.get(
    "PHP500_TARBALL",
    "/home/apt/repos_common/php-in-safe-rust/.app-tests/.temp/oracle/"
    "build-5.0.0/php-5.0.0.tar.gz")
SRC = "php-5.0.0/ext/mbstring/libmbfl/filters/html_entities.c"
SPAN = (37, 290)
SPAN_SHA = "734afebb8f33375d1de03bf47b9882ccc062315994ef328e5ff74cf1e4d66afb"

_ROW_RX = re.compile(rb'^\s*\{\s*"([^"]*)"\s*,\s*(-?\d+)\s*\}\s*,?\s*$')
_END_RX = re.compile(rb'^\s*\{\s*NULL\s*,\s*(-?\d+)\s*\}')

# Each shipped copy's own shape, as written. All are asserted below.
C_RX = re.compile(r'^\t\{"([^"]*)",\s*(-?\d+)\},$')
RS_RX = re.compile(r'^\s*Ent \{ name: b"([^"]*)", code: (-?\d+) \},$')
PY_RX = re.compile(r'^    \("([^"]*)", (-?\d+)\),$')


def tarball_rows():
    """(name, code) for every entity in the cited span, from the tarball."""
    import hashlib
    raw = subprocess.run(["tar", "-xzOf", TARBALL, SRC],
                         capture_output=True, check=True).stdout
    lines = raw.split(b"\n")[SPAN[0] - 1:SPAN[1]]
    excerpt = b"\n".join(lines) + b"\n"
    got = hashlib.sha256(excerpt).hexdigest()
    if got != SPAN_SHA:
        raise SystemExit(f"entity_table.py: span sha256 {got} != {SPAN_SHA}")
    out, saw_end = [], False
    for ln in lines:
        m = _ROW_RX.match(ln)
        if m:
            out.append((m.group(1).decode("ascii"), int(m.group(2))))
        elif _END_RX.match(ln.split(b"/*")[0]):
            saw_end = True
    if not saw_end:
        raise SystemExit("entity_table.py: {NULL,-1} terminator not found")
    return out


def emit_c(rows):
    w = []
    w.append("/* ph45 -- ext/mbstring/libmbfl/filters/html_entities.{h,c},")
    w.append(" * FLATTENED (PROTOCOL_PHP.md B3 spelling 1).  GENERATED by")
    w.append(" * controls/entity_table.py from the pinned tarball; do not edit.")
    w.append(" *")
    w.append(" *   html_entities.h:33-36   mbfl_html_entity_entry")
    w.append(" *   html_entities.c:37-290  mbfl_html_entity_list, 251 entries")
    w.append(" *                           + the {NULL,-1} terminator")
    w.append(" *")
    w.append(" * ⚠ This is CONST DATA and not control flow.  It is 254 of the row's")
    w.append(" * 477 cited lines and the cheapest half of them: `spec.md`'s")
    w.append(" * kernel-overlap number is dominated by it, and NOTES.md §7 says so.")
    w.append(" */")
    w.append("#ifndef PH45_HTML_ENTITIES_H")
    w.append("#define PH45_HTML_ENTITIES_H")
    w.append("")
    w.append("/* ===================== html_entities.h:33-36 ====================== */")
    w.append("typedef struct _mbfl_html_entity_entry {")
    w.append("\tchar *  name;")
    w.append("\tint     code;")
    w.append("} mbfl_html_entity_entry;")
    w.append("")
    w.append("/* ===================== html_entities.c:37-290 ===================== */")
    w.append("static const mbfl_html_entity_entry mbfl_html_entity_list[] = {")
    for n, c in rows:
        w.append('\t{"%s", %d},' % (n, c))
    w.append("\t{NULL,         -1}  /* mark end of table */")
    w.append("};")
    w.append("")
    w.append("#endif /* PH45_HTML_ENTITIES_H */")
    return "\n".join(w) + "\n"


def emit_rust(rows, indent="    "):
    """Just the array literal body -- the rungs wrap it themselves."""
    return "\n".join('%sEnt { name: b"%s", code: %d },' % (indent, n, c)
                     for n, c in rows) + "\n"


def _parse(path, rx):
    out = []
    with open(path, "r", encoding="utf-8") as fh:
        for ln in fh:
            m = rx.match(ln.rstrip("\n"))
            if m:
                out.append((m.group(1), int(m.group(2))))
    return out


SHIPPED = [("c/mbfl__html_entities.h", C_RX), ("model.py", PY_RX),
           ("safe_naive.rs", RS_RX), ("safe_tuned.rs", RS_RX),
           ("unsafe.rs", RS_RX), ("verus.rs", RS_RX)]


def check(rows, mutate=False):
    want = list(rows)
    if mutate:                              # the must-fire negative
        want[17] = (want[17][0], want[17][1] + 1)
    bad = 0
    for rel, rx in SHIPPED:
        p = os.path.join(ROW, rel)
        if not os.path.exists(p):
            print(f"  MISSING  {rel}")
            bad += 1
            continue
        got = _parse(p, rx)
        ok = got == want
        print(f"  {'ok  ' if ok else 'FAIL'} {rel:28s} {len(got):3d} entries")
        if not ok:
            bad += 1
            if len(got) == len(want):
                for i, (a, b) in enumerate(zip(got, want)):
                    if a != b:
                        print(f"        first difference at {i}: {a} != {b}")
                        break
    return bad


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit", choices=("c", "rust"))
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args()
    rows = tarball_rows()
    if a.emit == "c":
        sys.stdout.write(emit_c(rows))
        return 0
    if a.emit == "rust":
        sys.stdout.write(emit_rust(rows))
        return 0
    print(f"tarball span {SPAN[0]}-{SPAN[1]} sha256 ok, {len(rows)} entities, "
          f"max name {max(len(n) for n, _ in rows)}, "
          f"codes {min(c for _, c in rows)}..{max(c for _, c in rows)}")
    bad = check(rows)
    print(f"  -> {'PASS' if bad == 0 else 'FAIL'}: {bad} shipped table(s) differ "
          f"from the tarball")
    if a.selftest:
        print("MUST-FIRE negative: one entity's code bumped by 1 --")
        nbad = check(rows, mutate=True)
        print(f"  -> {'PASS' if nbad == len(SHIPPED) else 'FAIL'}: "
              f"{nbad}/{len(SHIPPED)} shipped tables rejected the mutant")
        if nbad != len(SHIPPED):
            return 1
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
