#!/usr/bin/env python3
"""p13 control: THE LIBRARY AXIS, four ways, on TERMINATION rather than speed.

`.memory/01-ladder.md` finding 9 (p11): a library term, a spelling term and a
safety term are three different things, and **the routine must be named beside
every rate**. p11 separated them on a NUL *scan* and on speed. p13 separates
them on a bounded *copy* and on **termination behaviour**, which is what the
pattern is about:

    routine                       terminates?              zero-fills?
    hand loop (= the rungs)       only if you write it     yes, to DST_CAP
    strncpy(dst, src, DST_CAP)    NO when slen >= DST_CAP  yes, to DST_CAP
    strlcpy(dst, src, DST_CAP)    ALWAYS                   no
    snprintf(dst, DST_CAP, "%s")  ALWAYS                   no

**All four print the same checksum**, which is what makes this a matched
comparison rather than four benchmarks: `d` is `min(slen, DST_CAP - 1)` for
every one of them once the termination store is present, and `dst[0]` is the
same byte.

⚠ **THIS PROBE KEEPS THE NARROW `d` + `dst[0]` FOLD THAT THE RUNGS DROPPED AT
TASK_046, and it has to.** The rungs now fold the destination's whole extent,
which is what makes their checksum an oracle for the copy. Here that would
break the comparison rather than strengthen it: `strlcpy` and `snprintf` do
**not** zero-fill, so `dst[n+1 .. DST_CAP]` holds whatever the previous string
left there, and a full-extent fold would make the four routines disagree for a
reason that has nothing to do with their cost. The narrow fold is what makes
"only the routine moves" true. Consequence, stated rather than buried: the
absolute levels in this control are NOT comparable to the ladder's per-call
figures in ../NOTES.md 4, which carry a 32-byte fold per string; what IS
comparable is every DIFFERENCE inside this table, because the fold term is
identical in all six columns and cancels.

So the only thing that moves is the routine, and the difference of
two rates is a *library* difference with both routines named.

THE PREDICTION TASK_043 ASKS TO TEST:

    strncpy's cost is FLAT in the source length and LINEAR in DST_CAP
    -- copying a 3-byte string into a 32-byte buffer costs the same as copying
    a 31-byte one --

which is the half of `strncpy` nobody expects, and if it holds it is the
pattern's largest single effect. The `--cap 256` sweep (p04's `RING_CAP = 60`
is the precedent) is what turns "linear in DST_CAP" from a story into a number.

    python3 patterns/p13-strncpy-trunc/controls/library_axis.py
    python3 patterns/p13-strncpy-trunc/controls/library_axis.py --caps 32,64,256

Scratch under `.temp/p13/library/` (binaries deleted by the caller;
`.temp/p13/library/library_axis.<cc>.json` is the evidence and stays).

⚠ Not a rung and not in the matrix. `strncpy(`, `strlcpy(` and `snprintf(` are
in ../spec.md's `idiom.forbidden` precisely so that this comparison lives here
and cannot leak into the R1-vs-R1h column. This probe also defines
`_GNU_SOURCE`, which no shipped rung does -- `strlcpy` links on glibc 2.39 but
is not declared under a bare `-std=c99`.
"""

import argparse
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
SCRATCH = os.path.join(REPO, ".temp", "p13", "library")
GCC = "/usr/bin/gcc"
CLANG = os.path.expanduser("~/tools/llvm/bin/clang")
VALGRIND = os.path.expanduser("~/tools/valgrind/bin/valgrind")

PROBE_C = r"""
/* p13 library-axis probe. GENERATED by controls/library_axis.py -- edit that.
 *
 * Four copy routines behind one kernel shape, all with the TERMINATION STORE
 * present, so all four return the same checksum and only the routine differs.
 * DST_CAP comes from -DDST_CAP so the same source measures every capacity.
 *
 * The `__asm__ volatile` in the repetition loop is not decoration: gcc CSEs a
 * pure `noinline` call out of the loop, which is how p13's phase-0 probe first
 * measured 6.28 Ir/call for 64 strings. See ../NOTES.md 0.
 */
#define _GNU_SOURCE
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef DST_CAP
#define DST_CAP 32
#endif

#define KERNEL(NAME, COPY)                                                    \
__attribute__((noinline))                                                     \
uint64_t NAME(const uint8_t *buf, size_t off, size_t len)                     \
{                                                                             \
    uint8_t dst[DST_CAP];                                                     \
    size_t nstr, s, p, q, i, slen, n, d;                                      \
    uint64_t acc = 0;                                                         \
    (void)i; (void)n;                                                         \
    if (len < 4) return 0;                                                    \
    nstr = (size_t)buf[off] + 256 * (size_t)buf[off + 1]                      \
        + 65536 * (size_t)buf[off + 2] + 16777216 * (size_t)buf[off + 3];     \
    if (nstr == 0) return 0;                                                  \
    p = 4;                                                                    \
    for (s = 0; s < nstr; s++) {                                              \
        q = p;                                                                \
        while (q < len) { if (buf[off + q] == 0) break; q = q + 1; }           \
        slen = q - p;                                                         \
        n = slen < DST_CAP ? slen : DST_CAP;                                  \
        COPY                                                                  \
        dst[DST_CAP - 1] = 0;                                                 \
        d = 0;                                                                \
        while (dst[d] != 0) d = d + 1;                                        \
        acc = acc * 31 + (uint64_t)d;                                         \
        acc = acc * 31 + (uint64_t)dst[0];                                    \
        if (q >= len) break;                                                  \
        p = q + 1;                                                            \
        if (p >= len) break;                                                  \
    }                                                                         \
    return acc * 31 + (uint64_t)nstr;                                         \
}

/* 1. the hand loop -- byte for byte what every p13 rung spells out */
KERNEL(k_hand,
    for (i = 0; i < n; i++) dst[i] = buf[off + p + i];
    for (i = n; i < DST_CAP; i++) dst[i] = 0;
)
/* 1b. the hand loop with the ZERO-FILL DELETED and nothing else changed --
 *     copy n bytes, then terminate. Same checksum: for slen < DST_CAP the
 *     terminator lands at dst[slen] where the fill would have put one, and for
 *     slen >= DST_CAP `dst[DST_CAP-1] = 0` below does it. `k_hand - k_handnofill`
 *     is therefore THE ZERO-FILL'S OWN COST, exactly isolated. */
KERNEL(k_handnofill,
    for (i = 0; i < n; i++) dst[i] = buf[off + p + i];
    if (n < DST_CAP) dst[n] = 0;
)
/* 1c. the same again with the byte copy replaced by memcpy, so that
 *     `k_handnofill - k_memcpy` is the COPY's hand-vs-library term with the
 *     fill absent from both. */
KERNEL(k_memcpy,
    memcpy((char *)dst, (const char *)(buf + off + p), n);
    if (n < DST_CAP) dst[n] = 0;
)
/* 2. the real thing */
KERNEL(k_strncpy,
    strncpy((char *)dst, (const char *)(buf + off + p), DST_CAP);
)
/* 3. always terminates, never zero-fills */
KERNEL(k_strlcpy,
    strlcpy((char *)dst, (const char *)(buf + off + p), DST_CAP);
)
/* 4. always terminates, parses a format string */
KERNEL(k_snprintf,
    snprintf((char *)dst, DST_CAP, "%s", (const char *)(buf + off + p));
)

static size_t build_window(uint8_t *w, uint32_t nstr, size_t slen)
{
    size_t p = 4, i;
    uint32_t s;
    w[0] = (uint8_t)(nstr & 255);
    w[1] = (uint8_t)((nstr >> 8) & 255);
    w[2] = (uint8_t)((nstr >> 16) & 255);
    w[3] = (uint8_t)((nstr >> 24) & 255);
    for (s = 0; s < nstr; s++) {
        for (i = 0; i < slen; i++)
            w[p++] = (uint8_t)(1 + ((s * 131u + i * 17u) % 254u));
        w[p++] = 0;
    }
    return p;
}

int main(int argc, char **argv)
{
    uint32_t nstr;
    size_t slen, iters, wlen, it;
    uint8_t *w;
    uint64_t acc = 0;
    uint64_t (*k)(const uint8_t *, size_t, size_t) = 0;

    if (argc != 5) { fprintf(stderr, "usage: %s routine nstr slen iters\n", argv[0]); return 2; }
    if      (!strcmp(argv[1], "hand"))     k = k_hand;
    else if (!strcmp(argv[1], "handnofill")) k = k_handnofill;
    else if (!strcmp(argv[1], "memcpy"))   k = k_memcpy;
    else if (!strcmp(argv[1], "strncpy"))  k = k_strncpy;
    else if (!strcmp(argv[1], "strlcpy"))  k = k_strlcpy;
    else if (!strcmp(argv[1], "snprintf")) k = k_snprintf;
    else { fprintf(stderr, "unknown routine %s\n", argv[1]); return 2; }
    nstr  = (uint32_t)strtoul(argv[2], NULL, 10);
    slen  = (size_t)strtoul(argv[3], NULL, 10);
    iters = (size_t)strtoul(argv[4], NULL, 10);

    w = (uint8_t *)malloc(16 + (size_t)nstr * (slen + 1));
    if (!w) return 6;
    wlen = build_window(w, nstr, slen);
    for (it = 0; it < iters; it++) {
        __asm__ volatile ("" : "+r" (w) : : "memory");
        acc = acc * 31 + k(w, 0, wlen);
    }
    printf("%llu\n", (unsigned long long)acc);
    free(w);
    return 0;
}
"""

ROUTINES = ("hand", "handnofill", "memcpy", "strncpy", "strlcpy", "snprintf")
NSTR = 32
LENS = (1, 4, 8, 16, 24, 31, 32, 64)


def sh(cmd):
    r = subprocess.run(cmd, capture_output=True, text=True)
    return r.returncode, r.stdout, r.stderr


def cg_ir(binary, args, tag):
    out = os.path.join(SCRATCH, f"cg.{tag}.out")
    rc, o, e = sh([VALGRIND, "--tool=callgrind", "--callgrind-out-file=" + out,
                   "-q", binary] + [str(a) for a in args])
    if rc != 0:
        raise SystemExit(f"callgrind failed rc={rc}: {e[:400]}")
    tot = None
    with open(out) as f:
        for ln in f:
            if ln.startswith(("summary:", "totals:")):
                tot = int(ln.split()[1])
    os.remove(out)
    return tot


def marginal(binary, routine, slen, lo=100, hi=200):
    a = cg_ir(binary, [routine, NSTR, slen, lo], f"{routine}.{slen}.lo")
    b = cg_ir(binary, [routine, NSTR, slen, hi], f"{routine}.{slen}.hi")
    return (b - a) / float(hi - lo)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--caps", default="32,256",
                    help="comma-separated DST_CAP values (default 32,256)")
    ap.add_argument("--cc", default="gcc", choices=["gcc", "clang"])
    a = ap.parse_args()
    caps = [int(c) for c in a.caps.split(",")]
    cc = GCC if a.cc == "gcc" else CLANG
    os.makedirs(SCRATCH, exist_ok=True)
    src = os.path.join(SCRATCH, "probe.c")
    with open(src, "w") as f:
        f.write(PROBE_C)

    res = {"cc": a.cc, "nstr": NSTR, "lens": list(LENS), "caps": caps, "ir": {}}
    for cap in caps:
        binary = os.path.join(SCRATCH, f"probe.{a.cc}.cap{cap}")
        rc, o, e = sh([cc, "-std=c99", "-O3", "-Wall", "-Wextra",
                       f"-DDST_CAP={cap}", src, "-o", binary])
        if rc != 0:
            print((o + e)[:3000])
            raise SystemExit("build failed")
        # one checksum sanity run: all four routines must agree
        sums = {r: sh([binary, r, str(NSTR), "40", "3"])[1].strip()
                for r in ROUTINES}
        agree = len(set(sums.values())) == 1
        print(f"\n=== DST_CAP = {cap} ({a.cc} -O3) ===")
        print(f"  checksum agreement across the four routines at slen=40: "
              f"{'YES' if agree else 'NO ' + str(sums)}  -> {sums['hand']}")
        res["ir"][str(cap)] = {"agree": agree, "checksums": sums, "rows": {}}
        print(f"  {'slen':>5s} " + " ".join(f"{r:>11s}" for r in ROUTINES)
              + "     (Ir per STRING)")
        for slen in LENS:
            row = {}
            for r in ROUTINES:
                row[r] = marginal(binary, r, slen) / NSTR
            res["ir"][str(cap)]["rows"][str(slen)] = row
            print(f"  {slen:5d} " + " ".join(f"{row[r]:11.4f}" for r in ROUTINES))
        os.remove(binary)

    out = os.path.join(SCRATCH, f"library_axis.{a.cc}.json")
    with open(out, "w") as f:
        json.dump(res, f, indent=1)
    print(f"\nwrote {out}")

    # --- the two claims, stated as arithmetic ---
    for cap in caps:
        rows = res["ir"][str(cap)]["rows"]
        for r in ROUTINES:
            below = [rows[str(l)][r] for l in LENS if l < cap]
            if len(below) >= 2:
                print(f"  cap={cap:4d} {r:9s} Ir/string over slen<{cap}: "
                      f"{min(below):.4f}..{max(below):.4f}  "
                      f"spread {max(below)-min(below):.4f}")
    if len(caps) >= 2:
        lo, hi = min(caps), max(caps)
        print(f"\n  --- the DST_CAP term, isolated: same source, same slen, "
              f"cap {lo} -> {hi} ---")
        for r in ROUTINES:
            for slen in (1, 8, 16):
                l = res["ir"][str(lo)]["rows"][str(slen)][r]
                h = res["ir"][str(hi)]["rows"][str(slen)][r]
                print(f"  slen={slen:2d}: {r:11s} {l:9.4f} -> {h:9.4f} "
                      f"= {h - l:+8.4f} Ir  = {(h - l) / (hi - lo):+.4f} "
                      f"per extra DST_CAP byte")
    print(f"\n  --- the ZERO-FILL's own cost: k_hand - k_handnofill (exact, "
          f"matched) ---")
    for cap in caps:
        rows = res["ir"][str(cap)]["rows"]
        vals = {l: rows[str(l)]["hand"] - rows[str(l)]["handnofill"] for l in LENS}
        print(f"  cap={cap:4d}: " + "  ".join(f"L{l}={v:+.3f}" for l, v in vals.items()))
    print(f"\n  --- the COPY's hand-vs-library term, fill absent from both: "
          f"k_handnofill - k_memcpy ---")
    for cap in caps:
        rows = res["ir"][str(cap)]["rows"]
        vals = {l: rows[str(l)]["handnofill"] - rows[str(l)]["memcpy"] for l in LENS}
        print(f"  cap={cap:4d}: " + "  ".join(f"L{l}={v:+.3f}" for l, v in vals.items()))
    return 0


if __name__ == "__main__":
    sys.exit(main())
