#!/usr/bin/env python3
"""Generate p08's three controls into `.temp/p08/controls/`.

    python3 patterns/p08-overlap-move/controls/gen_controls.py

`.memory/05-layout.md` demand 11: **a source that does not verify cleanly, or
does not compile at all, cannot live in a pattern dir.** **`check_verus_contract`** (`check.py:2770`)
requires every `.rs` in the pattern dir with a `verus!` block to be pinned in
`verus.obligations`, `:1549` fails the gate for any pinned file reporting
errors, and `build.py`'s `--cell` list is closed `choices`, so a deliberately
broken control has nowhere to live in-tree. The prescribed arrangement is a
**committed generator** that derives the control from the shipped source by
exact-string substitution and asserts its own hit count, so it cannot drift, plus
a `NOTES.md` section carrying the diff, the commands and the measured output.
p17 §1c is the model; this is the same shape with three controls instead of one.

The three, and what each is for:

1. **`borrow_reject.rs`** -- the C program transliterated into safe Rust. It
   must **fail to compile**: `memcpy(scr + dr, scr, m - dr)` needs a `&[u8]` and
   a `&mut [u8]` into one buffer at the same time, which is `E0502`. This is
   p08's central claim and the only one in this project that is a *compile-time*
   result with no runtime cost to measure. Written from scratch rather than
   derived, because there is nothing in the shipped tree to derive it from --
   that is the point.

2. **`nonoverlap.rs`** -- R4 with `core::ptr::copy` swapped for
   `core::ptr::copy_nonoverlapping`, i.e. **unsafe Rust re-opening the C bug
   exactly**. Derived from `unsafe.rs` by one substitution. Run under Miri on
   `adversarial-overlap.bin` this is the first time the gate's Miri stage has
   been pointed at an *aliasing* UB rather than a bounds one.

3. **`fwd_loop.rs`** -- R2 with the reverse loop written forward. Derived from
   `safe_naive.rs` by one substitution. It is **safe, it compiles, it does not
   panic, and it is wrong**: the buffer is replicated instead of shifted. Safe
   Rust prevents the *undefined behaviour*; it does not prevent the *wrongness*,
   and a write-up that claims "Rust fixes this" without this control is
   overclaiming. This project has done that four times already.

Nothing here is built by `harness/build.py` and nothing here is measured. The
commands to run each are printed at the end.

**The `#[path]` rewrite, fixed at TASK_022.** The two derived controls used to
keep the shipped `#[path = "../../common/driver.rs"]`. The generated file sits
*three* levels under the repo root (`.temp/p08/controls/`) where the shipped
source sits two (`patterns/p08-overlap-move/`), so that path resolved to
`.temp/common/driver.rs` — a gitignored copy of `common/` that happens to exist
on this box and is byte-identical to the real one today. The controls therefore
compiled **by luck**, and on a fresh clone they would not compile at all
(TASK_021_REVIEW clean negative 9). `PATH_FIX` below rewrites it to
`../../../common/driver.rs`, the real file that `source_sha256` hashes, and it
is asserted like every other substitution so it cannot silently stop matching.
p16's generator has done this since it landed; this is the same fix.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PDIR = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(PDIR))
OUT = os.path.join(REPO, ".temp", "p08", "controls")

#: shipped -> generated. The generated file sits three levels under the repo
#: root, the shipped one two, so the relative `#[path]` needs one more `..`.
#: Applied to every *derived* control; asserted like any other substitution.
PATH_FIX = ('#[path = "../../common/driver.rs"]',
            '#[path = "../../../common/driver.rs"]')


def sub(src_name, out_name, pairs, header=None):
    """Copy `src_name` from the pattern dir to OUT with exact-string
    substitutions, asserting each pattern occurs exactly once. `PATH_FIX` is
    applied to every derived control and asserted the same way."""
    s = open(os.path.join(PDIR, src_name)).read()
    for old, new in [PATH_FIX] + list(pairs):
        n = s.count(old)
        assert n == 1, f"{out_name}: {n} hits (want 1) for {old!r}"
        s = s.replace(old, new)
    if header:
        s = header + s
    open(os.path.join(OUT, out_name), "w").write(s)
    print(f"  {out_name:20s} <- {src_name} "
          f"({len(pairs)} substitution(s) + the #[path] rewrite)")


# ---------------------------------------------------------------------------
# Control 1: the borrow-check rejection. Not derived -- written out.
#
# This is the C rung's move, transliterated as directly as safe Rust permits.
# `memcpy(dst, src, n)` is `dst.copy_from_slice(src)`, and the two slices are
# both into `scr`. There is no way to spell it.
BORROW_REJECT = r'''// p08 control 1 -- THE BORROW-CHECK REJECTION.  MUST NOT COMPILE.
//
// Generated by patterns/p08-overlap-move/controls/gen_controls.py.
//
// This is c/kernel.c's move transliterated into safe Rust as directly as the
// language permits:
//
//     memcpy(scr + dr, scr, m - dr);
//  -> scr[dr..m].copy_from_slice(&scr[0..m - dr]);
//
// `copy_from_slice` takes `&mut self` and `&[T]`, so the expression needs a
// mutable and a shared borrow of `scr` alive at the same time. rustc rejects it
// at compile time. There is no runtime check, no panic, and nothing to measure:
// the cost of this safety property is zero instructions because the program
// does not exist.
//
//     ~/.cargo/bin/rustc --crate-type=lib --edition 2021 borrow_reject.rs
//
// The three shapes below are the three ways a programmer reaches for it. All
// three fail; `split_at_mut` (which does compile) cannot express an overlapping
// move at all, and the only thing left is `copy_within` -- which is R3.

const SCR: usize = 4096;

// (1) the direct transliteration of `memcpy(scr + dr, scr, m - dr)`
pub fn move_right_a(scr: &mut [u8; SCR], dr: usize, m: usize) {
    scr[dr..m].copy_from_slice(&scr[0..m - dr]);
}

// (2) the same thing with the two borrows named, which is what a programmer
//     writes when (1) is rejected and they do not yet see why
pub fn move_right_b(scr: &mut [u8; SCR], dr: usize, m: usize) {
    let src: &[u8] = &scr[0..m - dr];
    let dst: &mut [u8] = &mut scr[dr..m];
    dst.copy_from_slice(src);
}

// (3) the raw-ish version: two slices of one array handed to a copy
pub fn move_right_c(scr: &mut [u8; SCR], dr: usize, m: usize) {
    let (lo, hi) = (&scr[..m - dr], &mut scr[dr..m]);
    hi.copy_from_slice(lo);
}
'''


# ---------------------------------------------------------------------------
# Control 4: the detection table. Three sanitiser configurations of the SAME
# `c/kernel.c`, differing only in the compiler and in `_FORTIFY_SOURCE`.
#
# `harness/check.py` stage 7 is the first line below -- gcc at -O1 with this
# box's default `_FORTIFY_SOURCE=3` -- and it reports **nothing**, because gcc
# rewrites the move to `__memcpy_chk` and ASan's `memcpy-param-overlap` check
# lives in its `memcpy` interceptor. The other two lines are the same source
# with that one flag turned off, and with clang (which does not fortify by
# default). Both fire. See model.py's `sanitizer_expect` docstring.
DETECT_SH = r'''#!/bin/bash
# p08 control 4 -- THE DETECTION TABLE. Generated by
# patterns/p08-overlap-move/controls/gen_controls.py.
#
# Same c/kernel.c, three sanitiser configurations. The first is the one
# harness/check.py stage 7 builds.
set -u
cd "$(dirname "$0")"
REPO=$(cd ../../.. && pwd)
IN=$REPO/patterns/p08-overlap-move/inputs/adversarial-overlap.bin
SRC="$REPO/common/driver.c $REPO/patterns/p08-overlap-move/c/kernel.c $REPO/patterns/p08-overlap-move/c/main.c"
INC="-I $REPO/common -I $REPO/patterns/p08-overlap-move/c"
COM="-std=c99 -O1 -g -fsanitize=address,undefined -DSLB_ISOLATED"

echo "=== (1) gcc, _FORTIFY_SOURCE=3 (this box's default; check.py stage 7) ==="
/usr/bin/gcc $COM -static-libasan -static-libubsan $INC $SRC -o san-gcc-f3 || exit 1
./san-gcc-f3 "$IN" > out-gcc-f3.txt 2>&1; echo "  exit=$?"; head -4 out-gcc-f3.txt | sed 's/^/  /'
echo "  kernel calls:"; objdump -d --no-show-raw-insn san-gcc-f3 \
  | awk '/<kernel>:/,/^$/' | grep -oE '<(__)?[a-z_]+(@plt)?>' | grep -i mem | sort | uniq -c | sed 's/^/    /'

echo "=== (2) gcc, -D_FORTIFY_SOURCE=0 -- the ONLY difference ==="
/usr/bin/gcc $COM -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -static-libasan -static-libubsan \
  $INC $SRC -o san-gcc-f0 || exit 1
./san-gcc-f0 "$IN" > out-gcc-f0.txt 2>&1; echo "  exit=$?"; head -4 out-gcc-f0.txt | sed 's/^/  /'
echo "  kernel calls:"; objdump -d --no-show-raw-insn san-gcc-f0 \
  | awk '/<kernel>:/,/^$/' | grep -oE '<(__)?[a-z_]+(@plt)?>' | grep -i mem | sort | uniq -c | sed 's/^/    /'

echo "=== (3) clang (does not default-fortify) ==="
"$HOME/tools/llvm/bin/clang" $COM -static-libsan $INC $SRC -o san-clang || exit 1
./san-clang "$IN" > out-clang.txt 2>&1; echo "  exit=$?"; head -4 out-clang.txt | sed 's/^/  /'

echo "=== (4) valgrind memcheck on the plain (unsanitised) build ==="
/usr/bin/gcc -std=c99 -O3 -g -DSLB_ISOLATED $INC $SRC -o plain-gcc || exit 1
"$HOME/tools/valgrind/bin/valgrind" --tool=memcheck --error-exitcode=9 ./plain-gcc "$IN" 2>&1 | head -12
'''


def main():
    os.makedirs(OUT, exist_ok=True)
    print("p08 controls ->", os.path.relpath(OUT, os.getcwd()))

    open(os.path.join(OUT, "borrow_reject.rs"), "w").write(BORROW_REJECT)
    print(f"  {'borrow_reject.rs':20s} <- written out (must NOT compile)")

    sub("unsafe.rs", "nonoverlap.rs",
        [("core::ptr::copy(p, p.add(dr), m - dr);",
          "core::ptr::copy_nonoverlapping(p, p.add(dr), m - dr);")],
        header="// p08 control 2 -- `copy_nonoverlapping` RE-OPENS THE C BUG.\n"
               "// Generated from unsafe.rs by controls/gen_controls.py; one\n"
               "// substitution, asserted to hit exactly once. Everything else,\n"
               "// including the driver loop, is R4's verbatim.\n"
               "//\n"
               "//   ~/.cargo/bin/rustc -C opt-level=3 -C debug-assertions=off \\\n"
               "//     -C codegen-units=1 -o nonoverlap nonoverlap.rs\n"
               "//   cargo +nightly miri run ...   (see NOTES.md 5)\n"
               "//\n"
               "// `copy_nonoverlapping`'s entire safety contract is the\n"
               "// non-overlap, and `d` comes from the file. This is the C bug,\n"
               "// in Rust, under `unsafe`, with no diagnostic anywhere in the\n"
               "// type system.\n")

    sub("safe_naive.rs", "fwd_loop.rs",
        [("    for j in (0..m - dr).rev() {", "    for j in 0..m - dr {")],
        header="// p08 control 3 -- SAFE, COMPILES, DOES NOT PANIC, AND WRONG.\n"
               "// Generated from safe_naive.rs by controls/gen_controls.py; one\n"
               "// substitution, asserted to hit exactly once. The reverse loop\n"
               "// is written forward, so each byte is read after it has already\n"
               "// been overwritten and the buffer is REPLICATED instead of\n"
               "// shifted.\n"
               "//\n"
               "//   ~/.cargo/bin/rustc -C opt-level=3 -C debug-assertions=off \\\n"
               "//     -C codegen-units=1 -o fwd_loop fwd_loop.rs\n"
               "//\n"
               "// Zero `unsafe`, zero undefined behaviour, zero panics, and a\n"
               "// different checksum from every other rung on any input where\n"
               "// the ranges overlap. Safe Rust prevents the UB; it does not\n"
               "// prevent the bug.\n")

    open(os.path.join(OUT, "detect.sh"), "w").write(DETECT_SH)
    os.chmod(os.path.join(OUT, "detect.sh"), 0o755)
    print(f"  {'detect.sh':20s} <- written out (the detection table)")

    print("""
run them:
  cd .temp/p08/controls
  ~/.cargo/bin/rustc --crate-type=lib --edition 2021 borrow_reject.rs   # MUST FAIL
  ~/.cargo/bin/rustc -C opt-level=3 -C debug-assertions=off -C codegen-units=1 \\
      -o nonoverlap nonoverlap.rs && ./nonoverlap ../../../patterns/p08-overlap-move/inputs/adversarial-overlap.bin
  ~/.cargo/bin/rustc -C opt-level=3 -C debug-assertions=off -C codegen-units=1 \\
      -o fwd_loop fwd_loop.rs && ./fwd_loop ../../../patterns/p08-overlap-move/inputs/adversarial-overlap.bin
  ./detect.sh                                    # the ASan / valgrind table
""")
    return 0


if __name__ == "__main__":
    sys.exit(main())
